#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Translate remaining French Javadoc comments to English in Java files.
"""

import os
import re
import glob

target_dirs = [
    os.path.join("C:\\Users\\SURFACE\\Desktop\\collabix\\backend\\src\\main\\java\\com\\trio\\backend", "dto"),
    os.path.join("C:\\Users\\SURFACE\\Desktop\\collabix\\backend\\src\\main\\java\\com\\trio\\backend", "controller"),
    os.path.join("C:\\Users\\SURFACE\\Desktop\\collabix\\backend\\src\\main\\java\\com\\trio\\backend", "service"),
    os.path.join("C:\\Users\\SURFACE\\Desktop\\collabix\\backend\\src\\main\\java\\com\\trio\\backend", "repository"),
]

replacements = [
    # === Core verb: Récupère -> Retrieves ===
    (r'Récupère toutes', 'Retrieves all'),
    (r'Récupère tous', 'Retrieves all'),
    (r'Récupère les', 'Retrieves the'),
    (r'Récupère un', 'Retrieves a'),
    (r'Récupère une', 'Retrieves a'),
    (r'Récupère le', 'Retrieves the'),
    (r'Récupère la', 'Retrieves the'),
    (r"Récupère l'", "Retrieves the "),
    (r'Récupère des', 'Retrieves'),
    (r'Récupère ', 'Retrieves '),

    # === Core verb: Compte -> Counts ===
    (r'Compte les', 'Counts the'),
    (r'Compte le', 'Counts the'),
    (r'Compte la', 'Counts the'),
    (r'Compte toutes', 'Counts all'),
    (r'Compte tous', 'Counts all'),

    # === Permet de -> Allows to ===
    (r'Permet de', 'Allows to'),

    # === Créer/Crée -> Create/Creates (bullet points) ===
    (r'- Créer un', '- Create a'),
    (r'- Créer', '- Create'),
    (r'- Récupérer un', '- Retrieve a'),
    (r'- Récupérer la', '- Retrieve the'),
    (r'- Récupérer', '- Retrieve'),
    (r'- Lister les', '- List the'),
    (r'- Mettre à jour les', '- Update the'),
    (r'- Mettre à jour un', '- Update a'),
    (r'- Mettre à jour', '- Update'),
    (r'- Supprimer', '- Delete'),

    # === Verbs in description contexts ===
    (r'Crée un nouveau', 'Creates a new'),
    (r'Crée un', 'Creates a'),

    # === French articles ===
    (r'Tous les', 'All'),
    (r'tous les', 'all'),
    (r'Toutes les', 'All'),
    (r'toutes les', 'all'),
    (r'le propriétaire', 'the owner'),
    (r'Le propriétaire', 'The owner'),
    (r'le statut', 'the status'),
    (r'Le statut', 'The status'),
    (r'le nom', 'the name'),
    (r'Le nom', 'The name'),
    (r'la date', 'the date'),
    (r'La date', 'The date'),
    (r'la liste', 'the list'),
    (r'La liste', 'The list'),
    (r'la réponse', 'the response'),
    (r'La réponse', 'The response'),
    (r'les informations', 'the information'),
    (r'Les informations', 'The information'),
    (r'les données', 'the data'),
    (r'Les données', 'The data'),
    (r'les membres', 'the members'),
    (r'Les membres', 'The members'),

    # === Possessives ===
    (r'son ID', 'its ID'),
    (r'son identifiant', 'its identifier'),
    (r'son statut', 'its status'),
    (r'son rôle', 'its role'),
    (r'sa date', 'its date'),
    (r'ses ressources', 'its resources'),
    (r'leur rôle', 'their role'),

    # === du -> of the ===
    (r'du propriétaire', 'of the owner'),
    (r'du workspace', 'of the workspace'),
    (r'du département', 'of the department'),
    (r'du projet', 'of the project'),
    (r'du destinataire', 'of the recipient'),
    (r'du membre', 'of the member'),
    (r'du service', 'of the service'),

    # === de la -> of the ===
    (r'de la task', 'of the task'),
    (r'de la permission', 'of the permission'),
    (r'de la liste', 'of the list'),
    (r'de la requête', 'of the request'),
    (r'de la base', 'of the base'),

    # === d'un -> of a / of an ===
    (r"d'un utilisateur", 'of a user'),
    (r"d'un workspace", 'of a workspace'),
    (r"d'un département", 'of a department'),
    (r"d'un projet", 'of a project'),
    (r"d'un propriétaire", 'of an owner'),
    (r"d'un destinataire", 'of a recipient'),
    (r"d'un acteur", 'of an actor'),
    (r"d'un rôle", 'of a role'),

    # === d'une -> of a ===
    (r"d'une task", 'of a task'),
    (r"d'une équipe", 'of a team'),
    (r"d'une période", 'of a period'),
    (r"d'une date", 'of a date'),

    # === des -> of / of the ===
    (r'des Workspaces', 'of the Workspaces'),
    (r'des projets', 'of projects'),
    (r'des membres', 'of members'),
    (r'des notifications', 'of notifications'),
    (r'des ressources', 'of resources'),
    (r'des tokens', 'of tokens'),
    (r'des tâches', 'of tasks'),
    (r'des règles', 'of the rules'),

    # === d' phrases ===
    (r"d'équipe", 'of team'),
    (r"d'utilisateur", 'of user'),
    (r"d'activation", 'of activation'),
    (r"d'accès", 'of access'),
    (r"d'échéance", 'of expiry'),

    # === Prepositions ===
    (r'par son ID', 'by its ID'),
    (r'par ID', 'by ID'),
    (r'par son identifiant', 'by its identifier'),
    (r'par sa valeur', 'by its value'),
    (r'par type', 'by type'),
    (r'par statut', 'by status'),
    (r'par date', 'by date'),
    (r'par l\'utilisateur', 'by the user'),

    (r'dans une équipe', 'in a team'),
    (r'dans un workspace', 'in a workspace'),
    (r'dans un département', 'in a department'),
    (r'dans un projet', 'in a project'),
    (r'dans le workspace', 'in the workspace'),

    (r'avec pagination', 'with pagination'),
    (r'avec chargement', 'with loading'),
    (r'avec vérification', 'with verification'),
    (r'avec le statut', 'with the status'),
    (r'avec le rôle', 'with the role'),

    (r'pour une période', 'for a period'),
    (r"pour l'utilisateur", 'for the user'),
    (r'pour le reporting', 'for reporting'),
    (r"pour la génération", 'for generation'),
    (r'pour la persistance', 'for persistence'),
    (r'pour la validation', 'for validation'),
    (r"pour l'accès", 'for access'),
    (r'pour le nettoyage', 'for cleaning'),
    (r'pour la purge', 'for purging'),
    (r'pour filtrer', 'to filter'),
    (r'pour éviter', 'to avoid'),
    (r'pour donner', 'to give'),
    (r'pour rester', 'to stay'),

    (r'sur une période', 'over a period'),
    (r'au workspace', 'to the workspace'),
    (r'au département', 'to the department'),

    (r'est référencé', 'is referenced'),
    (r'est actif', 'is active'),
    (r'est membre', 'is a member'),
    (r'est propriétaire', 'is the owner'),
    (r'est considérée', 'is considered'),

    (r'ou administrateur', 'or administrator'),

    (r'et initialiser', 'and initialize'),
    (r'et archiver', 'and archive'),

    (r'sont destinés', 'are intended'),

    (r"qu'elle appartient", 'that it belongs'),
    (r'qui correspond', 'that matches'),

    # === l'ID / l'utilisateur ===
    (r"l'ID of the", 'the ID of the'),
    (r"l'ID du", 'the ID of the'),
    (r"l'ID de l'", "the ID of the "),
    (r"l'utilisateur authentifié", 'the authenticated user'),
    (r"l'utilisateur actuellement", 'the currently'),
    (r"l'équipe", 'the team'),

    # === à phrases ===
    (r'à mettre à jour', 'to update'),
    (r'à supprimer', 'to delete'),
    (r'à une date', 'to a date'),
    (r'après connexion', 'after login'),
    (r"depuis la page", 'from the page'),
    (r'à un workspace', 'to a workspace'),

    (r'un nouveau', 'a new'),
    (r'un workspace', 'a workspace'),
    (r'un département', 'a department'),
    (r'un projet', 'a project'),

    # === Adjective translations ===
    (r'créées', 'created'),
    (r'créés', 'created'),
    (r'spécifié', 'specified'),
    (r'spécifiée', 'specified'),
    (r'spécifique', 'specific'),
    (r'spécifiques', 'specific'),
    (r'donnée', 'given'),
    (r'utilisée', 'used'),
    (r'utilisées', 'used'),
    (r'utilisé', 'used'),
    (r'utilisés', 'used'),
    (r'filtrées', 'filtered'),
    (r'filtrés', 'filtered'),
    (r'associées', 'associated'),
    (r'associés', 'associated'),
    (r'limitée', 'limited'),
    (r'limité', 'limited'),
    (r'obligatoire', 'required'),
    (r'optionnelle', 'optional'),
    (r'décroissante', 'descending'),
    (r'récente', 'recent'),
    (r'récents', 'recent'),
    (r'récentes', 'recent'),
    (r'complète', 'complete'),
    (r'complètes', 'complete'),
    (r'complété', 'completed'),
    (r'complétées', 'completed'),
    (r'complète', 'complete'),
    (r'entières', 'entire'),
    (r'entière', 'entire'),
    (r'présent', 'present'),
    (r'présente', 'present'),
    (r'présents', 'present'),
    (r'présentes', 'present'),
    (r'nécessaires', 'required'),
    (r'nécessaire', 'required'),
    (r'invalides', 'invalid'),
    (r'normales', 'normal'),
    (r'courant', 'current'),
    (r'courante', 'current'),

    # === Noun translations ===
    (r'la gestion', 'management'),
    (r'la création', 'creation'),
    (r'la modification', 'modification'),
    (r'la suppression', 'deletion'),
    (r'la lecture', 'reading'),
    (r'l\'écriture', 'writing'),
    (r'l\'authentification', 'authentication'),
    (r'la validation', 'validation'),
    (r'la vérification', 'verification'),
    (r'la persistance', 'persistence'),
    (r'la génération', 'generation'),
    (r'la révocation', 'revocation'),
    (r'la conversion', 'conversion'),
    (r'la couche', 'the layer'),
    (r'la séparation', 'separation'),
    (r'la présentation', 'presentation'),
    (r'l\'unicité', 'uniqueness'),
    (r'la cohérence', 'consistency'),
    (r'l\'isolement', 'isolation'),
    (r'l\'utilisateur', 'the user'),
    (r'l\'administrateur', 'the administrator'),
    (r'le contexte', 'the context'),
    (r'le travail', 'work'),
    (r'le module', 'the module'),
    (r'le nombre', 'the number'),
    (r'le scope', 'the scope'),
    (r'le statut', 'the status'),
    (r'le résultat', 'the result'),
    (r'le propriétaire', 'the owner'),
    (r'le rôle', 'the role'),
    (r'les paramètres', 'the parameters'),
    (r'les champs', 'the fields'),

    # === Various other patterns ===
    (r'Aucune donnée', 'No data'),
    (r'aucune donnée', 'no data'),
    (r'ne peut', 'cannot'),
    (r'ne peuvent', 'cannot'),
    (r'peut être', 'can be'),
    (r'peuvent être', 'can be'),
    (r'doit être', 'must be'),
    (r'doivent être', 'must be'),
    (r'va être', 'will be'),
    (r'va être', 'will be'),
    (r'afin de', 'in order to'),
    (r'grâce à', 'thanks to'),
    (r'via la chaîne', 'through the chain'),
    (r'via cette méthode', 'through this method'),
    (r'via les requêtes', 'through queries'),
    (r'via {@code', 'through {@code'),
    (r'à éviter', 'to avoid'),
    (r'correspondant', 'corresponding'),
    (r'correspondants', 'corresponding'),
    (r'suivantes', 'following'),
    (r'suivants', 'following'),
    (r'effectue les', 'performs the'),
    (r'effectuées', 'performed'),
    (r'effectués', 'performed'),
    (r'extraite', 'extracted'),
    (r'extrait', 'extracted'),
    (r'fournie', 'provided'),
    (r'fournies', 'provided'),
    (r'fourni', 'provided'),
    (r'fournis', 'provided'),
    (r'disposant', 'having'),
    (r'dispose', 'has'),
    (r'disposent', 'have'),
    (r'contenant', 'containing'),
    (r'contenu', 'content'),
    (r'contient', 'contains'),
    (r'contiennent', 'contain'),
    (r'permet', 'allows'),
    (r'permetta', 'will allow'),
    (r'permettait', 'allowed'),
    (r'permette', 'allow'),
    (r'permettez', 'allow'),
    (r'permet', 'allows'),

    # === Clean up specific known patterns ===
    (r'n\'est pas', 'is not'),
    (r'n\'existe pas', 'does not exist'),
    (r'ne sont pas', 'are not'),
    (r'ne sont', 'are not'),
    (r'n\'ont pas', 'do not have'),

    # === The dreaded "le/la" articles in context ===
    (r'le membre', 'the member'),
    (r'le workspace', 'the workspace'),
    (r'le projet', 'the project'),
    (r'le département', 'the department'),
    (r'le token', 'the token'),
    (r'le jour', 'the day'),
    (r'le cas', 'the case'),
    (r'le team', 'the team'),
    (r'le statut', 'the status'),
    (r'Le workspace', 'The workspace'),
    (r'Le projet', 'The project'),
    (r'Le département', 'The department'),
    (r'Le token', 'The token'),

    (r'la tâche', 'the task'),
    (r'la permission', 'the permission'),
    (r'la notification', 'the notification'),
    (r'la requête', 'the request'),
    (r'la méthode', 'the method'),
    (r'la réponse', 'the response'),
    (r'la donnée', 'the data'),
    (r'la page', 'the page'),

    (r'les tâches', 'the tasks'),
    (r'les projets', 'the projects'),
    (r'les équipes', 'the teams'),
    (r'les membres', 'the members'),
    (r'les notifications', 'the notifications'),
    (r'les permissions', 'the permissions'),
    (r'les méthodes', 'the methods'),
    (r'les données', 'the data'),
    (r'les tokens', 'the tokens'),
    (r'les endpoints', 'the endpoints'),

    # === "des" followed by entity ===
    (r'des Workspaces', 'of the Workspaces'),
    (r'des équipes', 'of teams'),
    (r'des projets', 'of projects'),
    (r'des tâches', 'of tasks'),

    # === Sentinels that end sentences ===
    (r'via la chaîne', 'through the chain'),
    (r'via le projet', 'through the project'),
    (r'via les', 'through the'),

    # === Clean up some very specific remaining French ===
    (r'Paramètres de pagination', 'Pagination parameters'),
    (r'paramètres de pagination', 'pagination parameters'),
    (r'Liste des', 'List of'),
    (r'liste des', 'list of'),

    # === Final cleanup for mixed French/English ===
    (r'of a équipe', 'of a team'),
    (r'les informations', 'the information'),
    (r'Les informations', 'The information'),
    (r'les commentaires', 'the comments'),
    (r'les activités', 'the activities'),
    (r'les handovers', 'the handovers'),
    (r'les projets', 'the projects'),
    (r'les tâches', 'the tasks'),
    (r'les pièces jointes', 'the attachments'),
    (r'les documents', 'the documents'),
    (r'les articles', 'the articles'),
    (r'les membres', 'the members'),
    (r'les notifications', 'the notifications'),
    (r'les équipes', 'the teams'),
    (r'les données', 'the data'),
    (r'les informations', 'the information'),
    (r'de l\'utilisateur', 'of the user'),
    (r'de l\'équipe', 'of the team'),
    (r'de l\'utilisateur', 'of the user'),
    (r'de l\'authentification', 'of authentication'),
    (r'de l\'accès', 'of access'),
    (r'de l\'écriture', 'of writing'),
    (r'de l\'interface', 'of the interface'),

    # === Additional patterns for remaining French ===
    (r'Identifiant de l\'activité', 'ID of the activity'),
    (r'Identifiant de la pièce jointe', 'ID of the attachment'),
    (r'Identifiant de l\'entrée', 'ID of the entry'),
    (r'Description textuelle de l\'activité', 'Textual description of the activity'),
    (r'Horodatage de l\'activité', 'Timestamp of the activity'),
    (r'Date de création de l\'article', 'Creation date of the article'),
    (r'Catégorie de l\'article', 'Category of the article'),
    (r'Nom de l\'assigné', 'Name of the assignee'),
    (r'Nom de l\'équipe', 'Team name'),
    (r'Nom du département', 'Department name'),
    (r'Nom du projet', 'Project name'),
    (r'Rôle du membre', 'Role of the member'),
    (r'Rôle du workspace', 'Workspace role'),
    (r'Statistiques des membres', 'Member statistics'),
    (r'Statistiques', 'Statistics'),
    (r'des équipes', 'of teams'),
    (r'du département', 'of the department'),
    (r'Département', 'Department'),
    (r'département', 'department'),
    (r'Équipe', 'Team'),
    (r'Tâche', 'Task'),
    (r'Tâches', 'Tasks'),
    (r'Activité', 'Activity'),
    (r'Activités', 'Activities'),
    (r'propriétaire', 'owner'),
    (r'Propriétaire', 'Owner'),
    (r'Destiné', 'Intended'),
    (r'Conçu', 'Designed'),
    (r'préservant', 'preserving'),
    (r'séparément', 'separately'),
    (r'respectées', 'respected'),
    (r'réutilise', 'reuses'),
    (r'chaîne', 'chain'),
    (r'délègue', 'delegates'),
    (r'Délègue', 'Delegates'),
    (r'déléguer', 'delegate'),
    (r'générique', 'generic'),
    (r'suivant', 'following'),
    (r'suivante', 'following'),
    (r'précédent', 'previous'),
    (r'précédents', 'previous'),
    (r'précédente', 'previous'),
    (r'précédentes', 'previous'),
    (r'Archivé', 'Archived'),
    (r'archivé', 'archived'),
    (r'Génère', 'Generates'),
    (r'génère', 'generates'),
    (r'généré', 'generated'),
    (r'générée', 'generated'),
    (r'générés', 'generated'),
    (r'générer', 'generate'),
    (r'normalisé', 'normalized'),
    (r'insensible', 'case-insensitive'),
    (r'décroissante', 'descending'),
    (r'croissante', 'ascending'),
    (r'présente', 'presents'),
    (r'représente', 'represents'),
    (r'représentant', 'representing'),
    (r'complète', 'complete'),
    (r'complètes', 'complete'),
    (r'complété', 'completed'),
    (r'complétées', 'completed'),
    (r"Moyenne d'activités", 'Average activities'),
    (r'Moyenne', 'Average'),
    (r'Widget résumé', 'Summary widget'),
    (r'Widget représentant', 'Widget representing'),
    (r'widget', 'widget'),
    (r"Ne contient pas de données inventées", 'Does not contain any invented data'),
    (r"information sur les projets", 'information about the projects'),
    (r"une équipe", 'a team'),
    (r"Une équipe", 'A team'),
    (r"l'équipe", 'the team'),
    (r"Les informations", 'The information'),
    (r"les informations", 'the information'),
    (r"Les données", 'The data'),
    (r"les données", 'the data'),
    (r"Les champs", 'The fields'),
    (r"les champs", 'the fields'),
    (r"Le rôle", 'The role'),
    (r"le rôle", 'the role'),
    (r"Le service", 'The service'),
    (r"de la requête", 'of the request'),
    (r"des requêtes", 'of requests'),
    (r"de la page", 'of the page'),
    (r"du module", 'of the module'),
    (r"du contrôle", 'of control'),
    (r"du contexte", 'of the context'),
    (r"de sécurité", 'security'),
    (r"de gestion", 'management'),
    (r"de transmission", 'handover'),
    (r"définie", 'defined'),
    (r"définies", 'defined'),
    (r"définit", 'defines'),
    (r"définitif", 'definitive'),
    (r"définitive", 'definitive'),
    (r"définitivement", 'permanently'),
    (r"couche", 'layer'),
    (r"présentation", 'presentation'),
    (r"séparation", 'separation'),
    (r"séparer", 'separate'),
    (r"séparé", 'separated'),
    (r"séparés", 'separated'),
    (r"correspond", 'corresponds'),
    (r"correspondant", 'corresponding'),
    (r"correspondants", 'corresponding'),
    (r"respectant", 'respecting'),
    (r"respecte", 'respects'),
    (r"pointant", 'pointing'),
    (r"encapsulés", 'encapsulated'),
    (r"externalisés", 'externalized'),
    (r"asynchrone", 'asynchronous'),
    (r"dépendance", 'dependency'),
    (r"dépend", 'depends'),
    (r"débogage", 'debugging'),
    (r"non bloquant", 'non-blocking'),
    (r"flux", 'flow'),
    (r"pilote", 'driver'),
    (r"expéditeur", 'sender'),
    (r"destinataire", 'recipient'),
    (r"Destinataire", 'Recipient'),
    (r"destinataires", 'recipients'),
    (r"corps", 'body'),
    (r"titre", 'title'),
    (r"lien", 'link'),
    (r"bouton", 'button'),
    (r"avertissement", 'warning'),
    (r"explication", 'explanation'),
    (r"indiquant", 'indicating'),
    (r"effectuée", 'performed'),
    (r"effectué", 'performed'),
    (r"effectuées", 'performed'),
    (r"effectués", 'performed'),
    (r"effectuent", 'perform'),
    (r"permettant", 'allowing'),
    (r"permettra", 'will allow'),
    (r"permette", 'allows'),
    (r"permettent", 'allow'),
    (r"Ajoute", 'Adds'),
    (r"Ajouter", 'Add'),
    (r"ajouté", 'added'),
    (r"ajoutés", 'added'),
    (r"ajoutée", 'added'),
    (r"ajoutées", 'added'),
    (r"rattaché", 'attached'),
    (r"rattachée", 'attached'),
    (r"rattachés", 'attached'),
    (r"rattachées", 'attached'),
    (r"vérifie", 'verifies'),
    (r"Vérifie", 'Verifies'),
    (r"vérifié", 'verified'),
    (r"vérifiée", 'verified'),
    (r"vérification", 'verification'),
    (r"vérifier", 'verify'),
    (r"vérifiant", 'verifying'),
    (r"validé", 'validated'),
    (r"validation", 'validation'),
    (r"initialiser", 'initialize'),
    (r"initialisé", 'initialized'),
    (r"initialisée", 'initialized'),
    (r"initialisées", 'initialized'),
    (r"initialisés", 'initialized'),
    (r"erreur", 'error'),
    (r"Erreur", 'Error'),
    (r"requête", 'request'),
    (r"Requête", 'Request'),
    (r"requêtes", 'requests'),
    (r"Requêtes", 'Requests'),
    (r"Réponse", 'Response'),
    (r"réponse", 'response'),
    (r"donnée", 'data'),
    (r"Données", 'Data'),
    (r"méthode", 'method'),
    (r"Méthode", 'Method'),
    (r"méthodes", 'methods'),
    (r"Méthodes", 'Methods'),
    (r"opération", 'operation'),
    (r"Opération", 'Operation'),
    (r"transaction", 'transaction'),
    (r"transactionnel", 'transactional'),
    (r"transactionnels", 'transactional'),
    (r"transactionnelle", 'transactional'),
    (r"transactionnelles", 'transactional'),
    (r"contexte", 'context'),
    (r"garantie", 'guaranteed'),
    (r"garantir", 'guarantee'),
    (r"isolement", 'isolation'),
    (r"cohérence", 'consistency'),
    (r"exécutées", 'executed'),
    (r"exécutée", 'executed'),
    (r"exécutés", 'executed'),
    (r"exécuté", 'executed'),
    (r"exécute", 'executes'),
    (r"exécuter", 'execute'),
    (r"exécutant", 'executing'),
    (r"Exécution", 'Execution'),
    (r"étape", 'step'),
    (r"étapes", 'steps'),
    (r"Étape", 'Step'),
    (r"Étapes", 'Steps'),
    (r"début", 'start'),
    (r"Actuellement", 'Currently'),
    (r"actuelle", 'current'),
    (r"actuels", 'current'),
    (r"actuelles", 'current'),
    (r"immuable", 'immutable'),
    (r"immuables", 'immutable'),
    (r"modifiable", 'modifiable'),
    (r"modifié", 'modified'),
    (r"modifiés", 'modified'),
    (r"modifiée", 'modified'),
    (r"modifiées", 'modified'),
    (r"modifier", 'modify'),
    (r"Modifier", 'Modify'),
    (r"Changement", 'Change'),
    (r"changements", 'changes'),
    (r"déplacement", 'movement'),
    (r"restant", 'remaining'),
    (r"restante", 'remaining'),
    (r"restants", 'remaining'),
    (r"restantes", 'remaining'),
    (r"Suppression", 'Deletion'),
    (r"suppression", 'deletion'),
    (r"Création", 'Creation'),
    (r"création", 'creation'),
    (r"créé", 'created'),
    (r"créée", 'created'),
    (r"créés", 'created'),
    (r"créées", 'created'),
    (r"Créé", 'Created'),
    (r"créer", 'create'),
    (r"Créer", 'Create'),
    (r"configurable", 'configurable'),
    (r"réutilisable", 'reusable'),
    (r"abstraite", 'abstract'),
    (r"implémentation", 'implementation'),
    (r"Implémentation", 'Implementation'),
    (r"implémente", 'implements'),
    (r"implémenter", 'implement'),
    (r"implémentée", 'implemented'),
    (r"implémentées", 'implemented'),
    (r"injection", 'injection'),
    (r"annotation", 'annotation'),
    (r"collaboratif", 'collaborative'),
    (r"collaborative", 'collaborative'),
    (r"héritage", 'inheritance'),
    (r"surcharge", 'overload'),
    (r"surcharger", 'overload'),
    (r"redéfinit", 'overrides'),
    (r"redéfinir", 'override'),
    (r"polymorphisme", 'polymorphism'),
    (r"encapsulation", 'encapsulation'),
    (r"instancier", 'instantiate'),
    (r"instancié", 'instantiated'),
    (r"instanciée", 'instantiated'),
    (r"déclenche", 'triggers'),
    (r"déclenché", 'triggered'),
    (r"déclenchée", 'triggered'),
    (r"déclencher", 'trigger'),
    (r"appel", 'call'),
    (r"appelé", 'called'),
    (r"appelée", 'called'),
    (r"appeler", 'call'),
    (r"retourne", 'returns'),
    (r"Retourne", 'Returns'),
    (r"retourné", 'returned'),
    (r"retournée", 'returned'),
    (r"renvoie", 'returns'),
    (r"Renvoie", 'Returns'),
    (r"renvoyé", 'returned'),
    (r"renvoyée", 'returned'),
    (r"levée", 'thrown'),
    (r"levé", 'thrown'),
    (r"levées", 'thrown'),
    (r"interrompt", 'interrupts'),
    (r"interrompu", 'interrupted'),
    (r"interrompre", 'interrupt'),
    (r"annule", 'cancels'),
    (r"annulé", 'canceled'),
    (r"annulée", 'canceled'),
    (r"annuler", 'cancel'),
    (r"planifié", 'scheduled'),
    (r"planifiée", 'scheduled'),
    (r"planifiés", 'scheduled'),
    (r"planifier", 'schedule'),
    (r"programmé", 'scheduled'),
    (r"programmée", 'scheduled'),
    (r"programmer", 'schedule'),
    (r"exécution", 'execution'),
    (r"récupère", 'retrieves'),
    (r"Récupère", 'Retrieves'),
    (r"récupérer", 'retrieve'),
    (r"Récupérer", 'Retrieve'),
    (r"enregistre", 'saves'),
    (r"Enregistre", 'Saves'),
    (r"enregistré", 'saved'),
    (r"enregistrée", 'saved'),
    (r"enregistrer", 'save'),
    (r"chargement", 'loading'),
    (r"charge", 'loads'),
    (r"chargé", 'loaded'),
    (r"chargée", 'loaded'),
    (r"charger", 'load'),
    (r"traitement", 'processing'),
    (r"traite", 'processes'),
    (r"traité", 'processed'),
    (r"traitée", 'processed'),
    (r"traiter", 'process'),
    (r"filtrage", 'filtering'),
    (r"filtre", 'filters'),
    (r"filtré", 'filtered'),
    (r"filtrée", 'filtered'),
    (r"filtrer", 'filter'),
    (r"trier", 'sort'),
    (r"trié", 'sorted'),
    (r"triée", 'sorted'),
    (r"tri", 'sort'),
    (r"paginer", 'paginate'),
    (r"paginé", 'paginated'),
    (r"paginée", 'paginated'),
    (r"pagination", 'pagination'),
    (r"assembler", 'assemble'),
    (r"assemblage", 'assembly'),
    (r"construit", 'builds'),
    (r"construire", 'build'),
    (r"construction", 'construction'),
    (r"fabrique", 'factory'),
    (r"fabriquer", 'create'),
    (r"usine", 'factory'),
    (r"singleton", 'singleton'),
    (r"prototype", 'prototype'),
    (r"adaptateur", 'adapter'),
    (r"adaptateur", 'adapter'),
    (r"observateur", 'observer'),
    (r"observable", 'observable'),
    (r"abonnement", 'subscription'),
    (r"abonné", 'subscriber'),
    (r"abonnée", 'subscriber'),
    (r"publier", 'publish'),
    (r"publié", 'published'),
    (r"publiée", 'published'),
    (r"publication", 'publication'),
    (r"notification", 'notification'),
    (r"notifier", 'notify'),
    (r"notifié", 'notified'),
    (r"notifiée", 'notified'),
    (r"envoi", 'sending'),
    (r"envoyer", 'send'),
    (r"envoyé", 'sent'),
    (r"envoyée", 'sent'),
    (r"envoie", 'sends'),
    (r"réception", 'reception'),
    (r"recevoir", 'receive'),
    (r"reçu", 'received'),
    (r"reçue", 'received'),
    (r"reçoit", 'receives'),
    (r"connexion", 'connection'),
    (r"connecter", 'connect'),
    (r"connecté", 'connected'),
    (r"connectée", 'connected'),
    (r"déconnexion", 'disconnection'),
    (r"déconnecter", 'disconnect'),
    (r"déconnecté", 'disconnected'),
    (r"déconnectée", 'disconnected'),
    (r"session", 'session'),
    (r"jeton", 'token'),
    (r"jetons", 'tokens'),
    (r"authentification", 'authentication'),
    (r"authentifier", 'authenticate'),
    (r"authentifié", 'authenticated'),
    (r"authentifiée", 'authenticated'),
    (r"autorisation", 'authorization'),
    (r"autoriser", 'authorize'),
    (r"autorisé", 'authorized'),
    (r"autorisée", 'authorized'),
    (r"habilitation", 'authorization'),
    (r"privilège", 'privilege'),
    (r"privilèges", 'privileges'),
    (r"permission", 'permission'),
    (r"permissions", 'permissions'),
    (r"révocation", 'revocation'),
    (r"révoquer", 'revoke'),
    (r"révoqué", 'revoked'),
    (r"révoquée", 'revoked'),
    (r"expiration", 'expiration'),
    (r"expire", 'expires'),
    (r"expiré", 'expired'),
    (r"expirée", 'expired'),
    (r"renouvellement", 'renewal'),
    (r"renouveler", 'renew'),
    (r"renouvelé", 'renewed'),
    (r"renouvelée", 'renewed'),
    (r"rafraîchir", 'refresh'),
    (r"rafraîchi", 'refreshed'),
    (r"rafraîchie", 'refreshed'),
    (r"régénérer", 'regenerate'),
    (r"régénéré", 'regenerated'),
    (r"régénérée", 'regenerated'),
    (r"préférences", 'preferences'),
    (r"paramètres", 'settings'),
    (r"configuration", 'configuration'),
    (r"configurer", 'configure'),
    (r"configuré", 'configured'),
    (r"configurée", 'configured'),
    (r"personnaliser", 'customize'),
    (r"personnalisé", 'customized'),
    (r"personnalisée", 'customized'),
    (r"personnalisables", 'customizable'),
    (r"internationalisation", 'internationalization'),
    (r"localisation", 'localization'),
    (r"traduction", 'translation'),
    (r"traduire", 'translate'),
    (r"traduit", 'translated'),
    (r"traduite", 'translated'),
    (r"encodage", 'encoding'),
    (r"décodage", 'decoding'),
    (r"encoder", 'encode'),
    (r"encoder", 'encode'),
    (r"décoder", 'decode'),
    (r"décodé", 'decoded'),
    (r"décodée", 'decoded'),
    (r"sérialisation", 'serialization'),
    (r"Sérialisation", 'Serialization'),
    (r"désérialisation", 'deserialization'),
    (r"sérialiser", 'serialize'),
    (r"sérialisé", 'serialized'),
    (r"sérialisée", 'serialized'),
    (r"désérialiser", 'deserialize'),
    (r"désérialisé", 'deserialized'),
    (r"désérialisée", 'deserialized'),
    (r"formater", 'format'),
    (r"formaté", 'formatted'),
    (r"formatée", 'formatted'),
    (r"validation", 'validation'),
    (r"valider", 'validate'),
    (r"validé", 'validated'),
    (r"validée", 'validated'),
    (r"invalide", 'invalid'),
    (r"invalides", 'invalid'),
    (r"incorrect", 'incorrect'),
    (r"incorrecte", 'incorrect'),
    (r"incorrectes", 'incorrect'),
    (r"incomplet", 'incomplete'),
    (r"incomplète", 'incomplete'),
    (r"incomplètes", 'incomplete'),
    (r"inattendu", 'unexpected'),
    (r"inattendue", 'unexpected'),
    (r"inattendues", 'unexpected'),
    (r"indisponible", 'unavailable'),
    (r"indisponibles", 'unavailable'),
    (r"illégal", 'illegal'),
    (r"illégale", 'illegal'),
    (r"illégales", 'illegal'),
    (r"interdit", 'forbidden'),
    (r"interdite", 'forbidden'),
    (r"interdites", 'forbidden'),
    (r"refusé", 'refused'),
    (r"refusée", 'refused'),
    (r"refusées", 'refused'),
    (r"échec", 'failure'),
    (r"échoué", 'failed'),
    (r"échouée", 'failed'),
    (r"échouées", 'failed'),
    (r"succès", 'success'),
    (r"réussi", 'successful'),
    (r"réussie", 'successful'),
    (r"réussites", 'successes'),
    (r"avertir", 'warn'),
    (r"averti", 'warned'),
    (r"information", 'information'),
    (r"Important", 'Important'),
    (r"important", 'important'),
    (r"importante", 'important'),
    (r"importants", 'important'),
    (r"importantes", 'important'),
    (r"nécessaire", 'necessary'),
    (r"nécessaires", 'necessary'),
    (r"obligatoire", 'mandatory'),
    (r"obligatoires", 'mandatory'),
    (r"requis", 'required'),
    (r"requise", 'required'),
    (r"requises", 'required'),
    (r"souhaité", 'desired'),
    (r"souhaitée", 'desired'),
    (r"souhaitées", 'desired'),
    (r"minimum", 'minimum'),
    (r"maximum", 'maximum'),
    (r"minimal", 'minimal'),
    (r"minimale", 'minimal'),
    (r"maximal", 'maximal'),
    (r"maximale", 'maximal'),
    (r"limite", 'limit'),
    (r"limites", 'limits'),
    (r"taille", 'size'),
    (r"volume", 'volume'),
    (r"poids", 'weight'),
    (r"hauteur", 'height'),
    (r"largeur", 'width'),
    (r"profondeur", 'depth'),
    (r"longueur", 'length'),
    (r"distance", 'distance'),
    (r"durée", 'duration'),
    (r"temps", 'time'),
    (r"moment", 'moment'),
    (r"instant", 'instant'),
    (r"période", 'period'),
    (r"périodes", 'periods'),
    (r"intervalle", 'interval'),
    (r"intervalles", 'intervals'),
    (r"fréquence", 'frequency'),
    (r"fréquences", 'frequencies'),
    (r"quotidien", 'daily'),
    (r"quotidienne", 'daily'),
    (r"hebdomadaire", 'weekly'),
    (r"mensuel", 'monthly'),
    (r"mensuelle", 'monthly'),
    (r"annuel", 'annual'),
    (r"annuelle", 'annual'),
    (r"trimestriel", 'quarterly'),
    (r"trimestrielle", 'quarterly'),
    (r"répéter", 'repeat'),
    (r"répété", 'repeated'),
    (r"répétée", 'repeated'),
    (r"planning", 'schedule'),
    (r"calendrier", 'calendar'),
    (r"agenda", 'agenda'),
    (r"échéance", 'deadline'),
    (r"échéances", 'deadlines'),
    (r"délai", 'deadline'),
    (r"délais", 'deadlines'),
    (r"report", 'postponement'),
    (r"reporté", 'postponed'),
    (r"reportée", 'postponed'),
    (r"retard", 'delay'),
    (r"retardé", 'delayed'),
    (r"retardée", 'delayed'),
    (r"avance", 'advance'),
    (r"avancé", 'advanced'),
    (r"avancée", 'advanced'),
    (r"priorité", 'priority'),
    (r"priorités", 'priorities'),
    (r"prioritaire", 'priority'),
    (r"prioritaires", 'priority'),
    (r"urgent", 'urgent'),
    (r"urgente", 'urgent'),
    (r"Urgent", 'Urgent'),
    (r"critique", 'critical'),
    (r"Critique", 'Critical'),
    (r"normal", 'normal'),
    (r"Normale", 'Normal'),
    (r"faible", 'low'),
    (r"élevé", 'high'),
    (r"élevée", 'high'),
    (r"élevés", 'high'),
    (r"élevées", 'high'),
    (r"moyen", 'medium'),
    (r"moyenne", 'medium'),
    (r"Moyenne", 'Medium'),
    (r"statut", 'status'),
    (r"Statut", 'Status'),
    (r"état", 'state'),
    (r"États", 'States'),
    (r"actif", 'active'),
    (r"Active", 'Active'),
    (r"actifs", 'active'),
    (r"inactif", 'inactive'),
    (r"inactive", 'inactive'),
    (r"inactifs", 'inactive'),
    (r"en attente", 'pending'),
    (r"en cours", 'in progress'),
    (r"terminé", 'completed'),
    (r"terminée", 'completed'),
    (r"terminés", 'completed'),
    (r"terminées", 'completed'),
    (r"finalisé", 'finalized'),
    (r"finalisée", 'finalized'),
    (r"finalisés", 'finalized'),
    (r"finalisées", 'finalized'),
    (r"clôturé", 'closed'),
    (r"clôturée", 'closed'),
    (r"clôturés", 'closed'),
    (r"clôturées", 'closed'),
    (r"ouvert", 'open'),
    (r"ouverte", 'open'),
    (r"ouverts", 'open'),
    (r"ouvertes", 'open'),
    (r"bloqué", 'blocked'),
    (r"bloquée", 'blocked'),
    (r"bloqués", 'blocked'),
    (r"bloquées", 'blocked'),
    (r"résolu", 'resolved'),
    (r"résolue", 'resolved'),
    (r"résolus", 'resolved'),
    (r"résolues", 'resolved'),
    (r"approuvé", 'approved'),
    (r"approuvée", 'approved'),
    (r"approuvés", 'approved'),
    (r"approuvées", 'approved'),
    (r"rejeté", 'rejected'),
    (r"rejetée", 'rejected'),
    (r"rejetés", 'rejected'),
    (r"rejetées", 'rejected'),
    (r"refusé", 'refused'),
    (r"refusée", 'refused'),
    (r"confirmé", 'confirmed'),
    (r"confirmée", 'confirmed'),
    (r"confirmés", 'confirmed'),
    (r"confirmées", 'confirmed'),
    (r"vérifié", 'verified'),
    (r"vérifiée", 'verified'),
    (r"vérifiés", 'verified'),
    (r"vérifiées", 'verified'),
    (r"accepté", 'accepted'),
    (r"acceptée", 'accepted'),
    (r"acceptés", 'accepted'),
    (r"acceptées", 'accepted'),
    (r"décliné", 'declined'),
    (r"déclinée", 'declined'),
    (r"annulé", 'canceled'),
    (r"annulée", 'canceled'),
    (r"annulés", 'canceled'),
    (r"annulées", 'canceled'),
    (r"brouillon", 'draft'),
    (r"brouillons", 'drafts'),
    (r"modèle", 'template'),
    (r"Modèle", 'Template'),
    (r"modèles", 'templates'),
    (r"Modèles", 'Templates'),
    (r"catégorie", 'category'),
    (r"Catégorie", 'Category'),
    (r"catégories", 'categories'),
    (r"Catégories", 'Categories'),
    (r"type", 'type'),
    (r"Type", 'Type'),
    (r"typage", 'typing'),
    (r"classement", 'classification'),
    (r"étiquette", 'label'),
    (r"étiquettes", 'labels'),
    (r"balise", 'tag'),
    (r"balises", 'tags'),
    (r"tag", 'tag'),
    (r"tags", 'tags'),
    (r"libellé", 'label'),
    (r"libellés", 'labels'),
    (r"description", 'description'),
    (r"descriptif", 'descriptive'),
    (r"résumé", 'summary'),
    (r"sommaire", 'summary'),
    (r"détail", 'detail'),
    (r"détails", 'details'),
    (r"Détails", 'Details'),
    (r"détaillé", 'detailed'),
    (r"détaillée", 'detailed'),
    (r"détaillés", 'detailed'),
    (r"détaillées", 'detailed'),
    (r"aperçu", 'preview'),
    (r"visuel", 'visual'),
    (r"visuelle", 'visual'),
    (r"graphique", 'graphical'),
    (r"graphiques", 'graphics'),
    (r"schéma", 'schema'),
    (r"schémas", 'schemas'),
    (r"diagramme", 'diagram'),
    (r"carte", 'map'),
    (r"tableau", 'table'),
    (r"tableaux", 'tables'),
    (r"liste", 'list'),
    (r"listes", 'lists'),
    (r"grille", 'grid'),
    (r"arbre", 'tree'),
    (r"fichier", 'file'),
    (r"fichiers", 'files'),
    (r"dossier", 'folder'),
    (r"dossiers", 'folders'),
    (r"répertoire", 'directory'),
    (r"répertoires", 'directories'),
    (r"chemin", 'path'),
    (r"chemins", 'paths'),
    (r"nom", 'name'),
    (r"noms", 'names'),
    (r"prénom", 'first name'),
    (r"prénoms", 'first names'),
    (r"adresse", 'address'),
    (r"adresses", 'addresses'),
    (r"téléphone", 'phone'),
    (r"téléphones", 'phones'),
    (r"email", 'email'),
    (r"e-mail", 'email'),
    (r"courriel", 'email'),
    (r"site", 'site'),
    (r"portable", 'mobile'),
    (r"mobile", 'mobile'),
    (r"fax", 'fax'),
    (r"code postal", 'zip code'),
    (r"ville", 'city'),
    (r"Ville", 'City'),
    (r"pays", 'country'),
    (r"Pays", 'Country'),
    (r"région", 'region'),
    (r"Région", 'Region'),
    (r"nationalité", 'nationality'),
    (r"langue", 'language'),
    (r"Langue", 'Language'),
    (r"langues", 'languages'),
    (r"culture", 'culture'),
    (r"fuseau horaire", 'timezone'),
    (r"devise", 'currency'),
    (r"monnaie", 'currency'),
    (r"format", 'format'),
    (r"version", 'version'),
    (r"Version", 'Version'),
    (r"révision", 'revision'),
    (r"révisions", 'revisions'),
    (r"historique", 'history'),
    (r"historiques", 'histories'),
    (r"journal", 'log'),
    (r"journaux", 'logs'),
    (r"journalisation", 'logging'),
    (r"journaliser", 'log'),
    (r"journalisé", 'logged'),
    (r"journalisée", 'logged'),
    (r"audit", 'audit'),
    (r"auditer", 'audit'),
    (r"audité", 'audited'),
    (r"auditée", 'audited'),
    (r"traçabilité", 'traceability'),
    (r"trace", 'trace'),
    (r"traces", 'traces'),
    (r"suivi", 'monitoring'),
    (r"surveillance", 'monitoring'),
    (r"supervision", 'supervision'),
    (r"administrer", 'administer'),
    (r"administration", 'administration'),
    (r"gouvernance", 'governance'),
    (r"conformité", 'compliance'),
    (r"réglementation", 'regulation'),
    (r"règlement", 'regulation'),
    (r"régle", 'rule'),
    (r"règles", 'rules'),
    (r"politique", 'policy'),
    (r"politiques", 'policies'),
    (r"procédure", 'procedure'),
    (r"procédures", 'procedures'),
    (r"processus", 'process'),
    (r"processus", 'process'),
    (r"flux", 'workflow'),
    (r"workflow", 'workflow'),
    (r"Workflow", 'Workflow'),
    (r"étape", 'step'),
    (r"étapes", 'steps'),
    (r"jalon", 'milestone'),
    (r"jalons", 'milestones'),
    (r"livrable", 'deliverable'),
    (r"livrables", 'deliverables'),
    (r"version", 'version'),
    (r"versions", 'versions'),
    (r"itération", 'iteration'),
    (r"itérations", 'iterations'),
    (r"sprint", 'sprint'),
    (r"sprints", 'sprints'),
    (r"backlog", 'backlog'),
    (r"product backlog", 'product backlog'),
    (r"sprint backlog", 'sprint backlog'),
    (r"user story", 'user story'),
    (r"user stories", 'user stories'),
    (r"critère d'acceptation", 'acceptance criterion'),
    (r"critères d'acceptation", 'acceptance criteria'),
    (r"définition of done", 'definition of done'),
    (r"Definition of Done", 'Definition of Done'),
    (r"vélocité", 'velocity'),
    (r"capacité", 'capacity'),
    (r"effort", 'effort'),
    (r"estimation", 'estimation'),
    (r"estimer", 'estimate'),
    (r"estimé", 'estimated'),
    (r"estimée", 'estimated'),
    (r"story points", 'story points'),
    (r"story point", 'story point'),
    (r"heures", 'hours'),
    (r"jours", 'days'),
    (r"semaines", 'weeks'),
    (r"mois", 'months'),
    (r"années", 'years'),

    # === MISSING PATTERNS from remaining analysis ===
    (r'Résumé', 'Summary'),
    (r'résumé', 'summary'),
    (r'général', 'general'),
    (r'générale', 'general'),
    (r'généraux', 'general'),
    (r'générales', 'general'),
    (r'liées', 'related'),
    (r'lié', 'related'),
    (r'liée', 'related'),
    (r'liés', 'related'),
    (r'encapsulée', 'encapsulated'),
    (r'encapsulé', 'encapsulated'),
    (r'encapsulés', 'encapsulated'),
    (r'encapsulées', 'encapsulated'),
    (r'agrégées', 'aggregated'),
    (r'agrégé', 'aggregated'),
    (r'agrégée', 'aggregated'),
    (r'agrégés', 'aggregated'),
    (r'Prénom', 'First name'),
    (r'prénom', 'first name'),
    (r'Rôle', 'Role'),
    (r'rôle', 'role'),
    (r'rôles', 'roles'),
    (r'Rôles', 'Roles'),
    (r'Équipe', 'Team'),
    (r'équipe', 'team'),
    (r'Équipes', 'Teams'),
    (r'membre', 'member'),
    (r'Membre', 'Member'),
    (r'membres', 'members'),
    (r'Membres', 'Members'),
    (r'Activité', 'Activity'),
    (r'activité', 'activity'),
    (r'Activités', 'Activities'),
    (r'activités', 'activities'),
    (r'Tâche', 'Task'),
    (r'tâche', 'task'),
    (r'Tâches', 'Tasks'),
    (r'Projet', 'Project'),
    (r'projet', 'project'),
    (r'Projets', 'Projects'),
    (r'projets', 'projects'),
    (r'Catégorie', 'Category'),
    (r'catégorie', 'category'),
    (r'catégories', 'categories'),
    (r'Commentaire', 'Comment'),
    (r'commentaire', 'comment'),
    (r'commentaires', 'comments'),
    (r'Document', 'Document'),
    (r'document', 'document'),
    (r'documents', 'documents'),
    (r'Notification', 'Notification'),
    (r'notification', 'notification'),
    (r'notifications', 'notifications'),
    (r'Information', 'Information'),
    (r'information', 'information'),
    (r'informations', 'information'),
    (r'Donnée', 'Data'),
    (r'Données', 'Data'),
    (r'Pièce jointe', 'Attachment'),
    (r'pièce jointe', 'attachment'),
    (r'pièces jointes', 'attachments'),
    (r'assigné', 'assignee'),
    (r'assignée', 'assigned'),
    (r'assignés', 'assigned'),
    (r'assignées', 'assigned'),
    (r'préservation', 'preservation'),
    (r'préserve', 'preserves'),
    (r'préserver', 'preserve'),
    (r'réutilisation', 'reuse'),
    (r'réutiliser', 'reuse'),
    (r'implique', 'involves'),
    (r'impliqué', 'involved'),
    (r'impliquée', 'involved'),
    (r'impliqués', 'involved'),
    (r'impliquées', 'involved'),
    (r'appartient', 'belongs'),
    (r'appartenir', 'belong'),
    (r'appartenance', 'belonging'),
    (r'contenant', 'containing'),
    (r'contenu', 'content'),
    (r'Contenu', 'Content'),
    (r'contenus', 'contents'),
    (r'contient', 'contains'),
    (r'disponible', 'available'),
    (r'disponibles', 'available'),
    (r'accessible', 'accessible'),
    (r'accessibles', 'accessible'),
    (r'visible', 'visible'),
    (r'visibles', 'visible'),
    (r'caché', 'hidden'),
    (r'cachée', 'hidden'),
    (r'cachés', 'hidden'),
    (r'cachées', 'hidden'),
    (r'privé', 'private'),
    (r'privée', 'private'),
    (r'privés', 'private'),
    (r'privées', 'private'),
    (r'public', 'public'),
    (r'publique', 'public'),
    (r'publiques', 'public'),
    (r'partagé', 'shared'),
    (r'partagée', 'shared'),
    (r'partagés', 'shared'),
    (r'partagées', 'shared'),
    (r'Étiquette', 'Label'),
    (r'étiquette', 'label'),
    (r'étiquettes', 'labels'),
    (r'libellé', 'label'),
    (r'Libellé', 'Label'),
    (r'libellés', 'labels'),
    (r'Brouillon', 'Draft'),
    (r'brouillon', 'draft'),
    (r'brouillons', 'drafts'),
    (r'Archive', 'Archive'),
    (r'archive', 'archive'),
    (r'archives', 'archives'),
    (r'archivage', 'archiving'),
    (r'Horaire', 'Schedule'),
    (r'horaire', 'schedule'),
    (r'horaires', 'schedules'),
    (r'Plage', 'Range'),
    (r'plage', 'range'),
    (r'plages', 'ranges'),
    (r'Journée', 'Day'),
    (r'journée', 'day'),
    (r'journées', 'days'),
    (r'Semaine', 'Week'),
    (r'semaine', 'week'),
    (r'Mois', 'Month'),
    (r'Trimestre', 'Quarter'),
    (r'trimestre', 'quarter'),
    (r'Année', 'Year'),
    (r'année', 'year'),
    (r'Aujourd\'hui', 'Today'),
    (r'aujourd\'hui', 'today'),
    (r'Hier', 'Yesterday'),
    (r'hier', 'yesterday'),
    (r'Demain', 'Tomorrow'),
    (r'demain', 'tomorrow'),
    (r'Maintenant', 'Now'),
    (r'maintenant', 'now'),
    (r'Récent', 'Recent'),
    (r'récent', 'recent'),
    (r'Récente', 'Recent'),
    (r'récente', 'recent'),
    (r'Récents', 'Recent'),
    (r'récents', 'recent'),
    (r'Récentes', 'Recent'),
    (r'récentes', 'recent'),
    (r'Prochain', 'Next'),
    (r'prochain', 'next'),
    (r'prochaine', 'next'),
    (r'prochains', 'next'),
    (r'prochaines', 'next'),
    (r'Précédent', 'Previous'),
    (r'précédent', 'previous'),
    (r'Précédente', 'Previous'),
    (r'précédente', 'previous'),
    (r'Précédents', 'Previous'),
    (r'précédents', 'previous'),
    (r'Précédentes', 'Previous'),
    (r'précédentes', 'previous'),
    (r'Suivant', 'Next'),
    (r'suivant', 'next'),
    (r'Suivante', 'Next'),
    (r'suivante', 'next'),
    (r'Suivants', 'Next'),
    (r'suivants', 'next'),
    (r'Suivantes', 'Next'),
    (r'suivantes', 'following'),
    (r'Premier', 'First'),
    (r'premier', 'first'),
    (r'Première', 'First'),
    (r'première', 'first'),
    (r'Premiers', 'First'),
    (r'premiers', 'first'),
    (r'Premières', 'First'),
    (r'premières', 'first'),
    (r'Dernier', 'Last'),
    (r'dernier', 'last'),
    (r'Dernière', 'Last'),
    (r'dernière', 'last'),
    (r'Derniers', 'Last'),
    (r'derniers', 'last'),
    (r'Dernières', 'Last'),
    (r'dernières', 'last'),
    (r'Tout', 'All'),
    (r'tout', 'all'),
    (r'Tous', 'All'),
    (r'tous', 'all'),
    (r'Toute', 'All'),
    (r'toute', 'all'),
    (r'Toutes', 'All'),
    (r'Chaque', 'Each'),
    (r'chaque', 'each'),
    (r'Quelque', 'Some'),
    (r'quelque', 'some'),
    (r'quelques', 'some'),
    (r'Plusieurs', 'Several'),
    (r'plusieurs', 'several'),
    (r'Certain', 'Certain'),
    (r'certain', 'certain'),
    (r'certaine', 'certain'),
    (r'certains', 'certain'),
    (r'certaines', 'certain'),
    (r'Autre', 'Other'),
    (r'autre', 'other'),
    (r'autres', 'other'),
    (r'Même', 'Same'),
    (r'même', 'same'),
    (r'mêmes', 'same'),
    (r'Différent', 'Different'),
    (r'différent', 'different'),
    (r'différente', 'different'),
    (r'différents', 'different'),
    (r'différentes', 'different'),
    (r'Principal', 'Main'),
    (r'principal', 'main'),
    (r'principale', 'main'),
    (r'principaux', 'main'),
    (r'principales', 'main'),
    (r'Second', 'Second'),
    (r'second', 'second'),
    (r'seconde', 'second'),
    (r'secondes', 'seconds'),
    (r'Supplémentaire', 'Additional'),
    (r'supplémentaire', 'additional'),
    (r'supplémentaires', 'additional'),
    (r'Additionnel', 'Additional'),
    (r'additionnel', 'additional'),
    (r'additionnelle', 'additional'),
    (r'additionnels', 'additional'),
    (r'additionnelles', 'additional'),
    (r'Optionnel', 'Optional'),
    (r'optionnel', 'optional'),
    (r'Optionnelle', 'Optional'),
    (r'optionnelle', 'optional'),
    (r'Optionnels', 'Optional'),
    (r'optionnels', 'optional'),
    (r'Optionnelles', 'Optional'),
    (r'optionnelles', 'optional'),
    (r'Obligatoire', 'Mandatory'),
    (r'obligatoire', 'mandatory'),
    (r'obligatoires', 'mandatory'),
    (r'Requis', 'Required'),
    (r'requis', 'required'),
    (r'Requise', 'Required'),
    (r'requise', 'required'),
    (r'Requises', 'Required'),
    (r'requises', 'required'),
    (r'Facultatif', 'Optional'),
    (r'facultatif', 'optional'),
    (r'facultative', 'optional'),
    (r'facultatifs', 'optional'),
    (r'facultatives', 'optional'),
    (r'Important', 'Important'),
    (r'important', 'important'),
    (r'importante', 'important'),
    (r'importants', 'important'),
    (r'importantes', 'important'),
    (r'Inutile', 'Unnecessary'),
    (r'inutile', 'unnecessary'),
    (r'Utile', 'Useful'),
    (r'utile', 'useful'),
    (r'utiles', 'useful'),
    (r'Nécessaire', 'Necessary'),
    (r'nécessaire', 'necessary'),
    (r'nécessaires', 'necessary'),
    (r'Indispensable', 'Essential'),
    (r'indispensable', 'essential'),
    (r'indispensables', 'essential'),
    (r'Essentiel', 'Essential'),
    (r'essentiel', 'essential'),
    (r'essentielle', 'essential'),
    (r'essentiels', 'essential'),
    (r'essentielles', 'essential'),
    (r'Évident', 'Obvious'),
    (r'évident', 'obvious'),
    (r'évidente', 'obvious'),
    (r'Simple', 'Simple'),
    (r'simple', 'simple'),
    (r'simples', 'simple'),
    (r'Complexe', 'Complex'),
    (r'complexe', 'complex'),
    (r'complexes', 'complex'),
    (r'Facile', 'Easy'),
    (r'facile', 'easy'),
    (r'faciles', 'easy'),
    (r'Difficile', 'Difficult'),
    (r'difficile', 'difficult'),
    (r'difficiles', 'difficult'),
    (r'Rapide', 'Fast'),
    (r'rapide', 'fast'),
    (r'rapides', 'fast'),
    (r'Lent', 'Slow'),
    (r'lent', 'slow'),
    (r'lente', 'slow'),
    (r'lents', 'slow'),
    (r'lentes', 'slow'),
    (r'long', 'long'),
    (r'longue', 'long'),
    (r'longs', 'long'),
    (r'longues', 'long'),
    (r'court', 'short'),
    (r'courte', 'short'),
    (r'courts', 'short'),
    (r'courtes', 'short'),
    (r'Grand', 'Large'),
    (r'grand', 'large'),
    (r'grande', 'large'),
    (r'grands', 'large'),
    (r'grandes', 'large'),
    (r'Petit', 'Small'),
    (r'petit', 'small'),
    (r'petite', 'small'),
    (r'petits', 'small'),
    (r'petites', 'small'),
    (r'Haut', 'High'),
    (r'haut', 'high'),
    (r'haute', 'high'),
    (r'hauts', 'high'),
    (r'hautes', 'high'),
    (r'Bas', 'Low'),
    (r'bas', 'low'),
    (r'basse', 'low'),
    (r'Élevé', 'High'),
    (r'élevé', 'high'),
    (r'Élevée', 'High'),
    (r'élevée', 'high'),
    (r'Élevés', 'High'),
    (r'élevés', 'high'),
    (r'Élevées', 'High'),
    (r'élevées', 'high'),
    (r'Faible', 'Low'),
    (r'faible', 'low'),
    (r'faibles', 'low'),
    (r'Moyen', 'Average'),
    (r'moyen', 'average'),
    (r'Moyenne', 'Average'),
    (r'moyenne', 'average'),
    (r'moyens', 'average'),
    (r'moyennes', 'average'),
    (r'Minimum', 'Minimum'),
    (r'minimum', 'minimum'),
    (r'Maximum', 'Maximum'),
    (r'maximum', 'maximum'),
    (r'Optimal', 'Optimal'),
    (r'optimal', 'optimal'),
    (r'optimale', 'optimal'),
    (r'optimaux', 'optimal'),
    (r'optimales', 'optimal'),
    (r'Standard', 'Standard'),
    (r'standard', 'standard'),
    (r'Normal', 'Normal'),
    (r'normal', 'normal'),
    (r'Normale', 'Normal'),
    (r'normale', 'normal'),
    (r'Normaux', 'Normal'),
    (r'normaux', 'normal'),
    (r'Normales', 'Normal'),
    (r'normales', 'normal'),
    (r'Spécial', 'Special'),
    (r'spécial', 'special'),
    (r'spéciale', 'special'),
    (r'spéciaux', 'special'),
    (r'spéciales', 'special'),
    (r'Particulier', 'Particular'),
    (r'particulier', 'particular'),
    (r'particulière', 'particular'),
    (r'particuliers', 'particular'),
    (r'particulières', 'particular'),
    (r'Général', 'General'),
    (r'général', 'general'),
    (r'Générale', 'General'),
    (r'générale', 'general'),
    (r'Généraux', 'General'),
    (r'généraux', 'general'),
    (r'Générales', 'General'),
    (r'générales', 'general'),
    (r'Complet', 'Complete'),
    (r'complet', 'complete'),
    (r'complète', 'complete'),
    (r'complets', 'complete'),
    (r'complètes', 'complete'),
    (r'Partiel', 'Partial'),
    (r'partiel', 'partial'),
    (r'partielle', 'partial'),
    (r'partiels', 'partial'),
    (r'partielles', 'partial'),
    (r'Incomplet', 'Incomplete'),
    (r'incomplet', 'incomplete'),
    (r'incomplète', 'incomplete'),
    (r'incomplets', 'incomplete'),
    (r'incomplètes', 'incomplete'),
    (r'Précis', 'Precise'),
    (r'précis', 'precise'),
    (r'précise', 'precise'),
    (r'précises', 'precise'),
    (r'Exact', 'Exact'),
    (r'exact', 'exact'),
    (r'exacte', 'exact'),
    (r'exacts', 'exact'),
    (r'exactes', 'exact'),
    (r'Approximatif', 'Approximate'),
    (r'approximatif', 'approximate'),
    (r'approximative', 'approximate'),
    (r'approximatifs', 'approximate'),
    (r'approximatives', 'approximate'),
    (r'Vide', 'Empty'),
    (r'vide', 'empty'),
    (r'vides', 'empty'),
    (r'Vierge', 'Blank'),
    (r'vierge', 'blank'),
    (r'Rempli', 'Filled'),
    (r'rempli', 'filled'),
    (r'remplie', 'filled'),
    (r'remplis', 'filled'),
    (r'remplies', 'filled'),
    (r'Manquant', 'Missing'),
    (r'manquant', 'missing'),
    (r'manquante', 'missing'),
    (r'manquants', 'missing'),
    (r'manquantes', 'missing'),
    (r'Présent', 'Present'),
    (r'présent', 'present'),
    (r'présente', 'presents'),
    (r'présents', 'present'),
    (r'présentes', 'present'),
    (r'Absent', 'Absent'),
    (r'absent', 'absent'),
    (r'absente', 'absent'),
    (r'absents', 'absent'),
    (r'absentes', 'absent'),
    (r'Inexistant', 'Non-existent'),
    (r'inexistant', 'non-existent'),
    (r'inexistante', 'non-existent'),
    (r'inexistants', 'non-existent'),
    (r'inexistantes', 'non-existent'),
    (r'Valide', 'Valid'),
    (r'valide', 'valid'),
    (r'valides', 'valid'),
    (r'Invalide', 'Invalid'),
    (r'invalide', 'invalid'),
    (r'invalides', 'invalid'),
    (r'Correct', 'Correct'),
    (r'correct', 'correct'),
    (r'correcte', 'correct'),
    (r'corrects', 'correct'),
    (r'correctes', 'correct'),
    (r'Incorrect', 'Incorrect'),
    (r'incorrect', 'incorrect'),
    (r'incorrecte', 'incorrect'),
    (r'incorrects', 'incorrect'),
    (r'incorrectes', 'incorrect'),
    (r'Faux', 'False'),
    (r'faux', 'false'),
    (r'fausse', 'false'),
    (r'fausses', 'false'),
    (r'Vrai', 'True'),
    (r'vrai', 'true'),
    (r'vraie', 'true'),
    (r'vraies', 'true'),
    (r'Connu', 'Known'),
    (r'connu', 'known'),
    (r'connue', 'known'),
    (r'connus', 'known'),
    (r'connues', 'known'),
    (r'Inconnu', 'Unknown'),
    (r'inconnu', 'unknown'),
    (r'inconnue', 'unknown'),
    (r'inconnus', 'unknown'),
    (r'inconnues', 'unknown'),
    (r'Clair', 'Clear'),
    (r'clair', 'clear'),
    (r'claire', 'clear'),
    (r'clairs', 'clear'),
    (r'claires', 'clear'),
    (r'Ambigu', 'Ambiguous'),
    (r'ambigu', 'ambiguous'),
    (r'ambiguë', 'ambiguous'),
    (r'ambigus', 'ambiguous'),
    (r'ambiguës', 'ambiguous'),
    (r'Logique', 'Logical'),
    (r'logique', 'logical'),
    (r'logiques', 'logical'),
    (r'Cohérent', 'Consistent'),
    (r'cohérent', 'consistent'),
    (r'cohérente', 'consistent'),
    (r'cohérents', 'consistent'),
    (r'cohérentes', 'consistent'),
    (r'Stable', 'Stable'),
    (r'stable', 'stable'),
    (r'stables', 'stable'),
    (r'Instable', 'Unstable'),
    (r'instable', 'unstable'),
    (r'instables', 'unstable'),
    (r'Sûr', 'Safe'),
    (r'sûr', 'safe'),
    (r'sûre', 'safe'),
    (r'sûrs', 'safe'),
    (r'sûres', 'safe'),
    (r'Sécurisé', 'Secure'),
    (r'sécurisé', 'secure'),
    (r'sécurisée', 'secure'),
    (r'sécurisés', 'secure'),
    (r'sécurisées', 'secure'),
    (r'Protégé', 'Protected'),
    (r'protégé', 'protected'),
    (r'protégée', 'protected'),
    (r'protégés', 'protected'),
    (r'protégées', 'protected'),
    (r'Vulnérable', 'Vulnerable'),
    (r'vulnérable', 'vulnerable'),
    (r'vulnérables', 'vulnerable'),
    (r'Exposé', 'Exposed'),
    (r'exposé', 'exposed'),
    (r'exposée', 'exposed'),
    (r'exposés', 'exposed'),
    (r'exposées', 'exposed'),
    (r'Isolé', 'Isolated'),
    (r'isolé', 'isolated'),
    (r'isolée', 'isolated'),
    (r'isolés', 'isolated'),
    (r'isolées', 'isolated'),
    (r'Groupé', 'Grouped'),
    (r'groupé', 'grouped'),
    (r'groupée', 'grouped'),
    (r'groupés', 'grouped'),
    (r'groupées', 'grouped'),
    (r'Organisé', 'Organized'),
    (r'organisé', 'organized'),
    (r'organisée', 'organized'),
    (r'organisés', 'organized'),
    (r'organisées', 'organized'),
    (r'Classé', 'Classified'),
    (r'classé', 'classified'),
    (r'classée', 'classified'),
    (r'classés', 'classified'),
    (r'classées', 'classified'),
    (r'Trié', 'Sorted'),
    (r'trié', 'sorted'),
    (r'triée', 'sorted'),
    (r'triés', 'sorted'),
    (r'triées', 'sorted'),
    (r'Filtré', 'Filtered'),
    (r'filtré', 'filtered'),
    (r'filtrée', 'filtered'),
    (r'filtrés', 'filtered'),
    (r'filtrées', 'filtered'),
    (r'Indexé', 'Indexed'),
    (r'indexé', 'indexed'),
    (r'indexée', 'indexed'),
    (r'indexés', 'indexed'),
    (r'indexées', 'indexed'),
    (r'Hashé', 'Hashed'),
    (r'hashé', 'hashed'),
    (r'hashée', 'hashed'),
    (r'hashés', 'hashed'),
    (r'hashées', 'hashed'),
    (r'Chiffré', 'Encrypted'),
    (r'chiffré', 'encrypted'),
    (r'chiffrée', 'encrypted'),
    (r'chiffrés', 'encrypted'),
    (r'chiffrées', 'encrypted'),
    (r'Déchiffré', 'Decrypted'),
    (r'déchiffré', 'decrypted'),
    (r'déchiffrée', 'decrypted'),
    (r'déchiffrés', 'decrypted'),
    (r'déchiffrées', 'decrypted'),
    (r'Compressé', 'Compressed'),
    (r'compressé', 'compressed'),
    (r'compressée', 'compressed'),
    (r'compressés', 'compressed'),
    (r'compressées', 'compressed'),
    (r'Décompressé', 'Decompressed'),
    (r'décompressé', 'decompressed'),
    (r'décompressée', 'decompressed'),
    (r'décompressés', 'decompressed'),
    (r'décompressées', 'decompressed'),
    (r'Encodé', 'Encoded'),
    (r'encodé', 'encoded'),
    (r'encodée', 'encoded'),
    (r'encodés', 'encoded'),
    (r'encodées', 'encoded'),
    (r'Décodé', 'Decoded'),
    (r'décodé', 'decoded'),
    (r'décodée', 'decoded'),
    (r'décodés', 'decoded'),
    (r'décodées', 'decoded'),
    (r'Converti', 'Converted'),
    (r'converti', 'converted'),
    (r'convertie', 'converted'),
    (r'convertis', 'converted'),
    (r'converties', 'converted'),
    (r'Transformé', 'Transformed'),
    (r'transformé', 'transformed'),
    (r'transformée', 'transformed'),
    (r'transformés', 'transformed'),
    (r'transformées', 'transformed'),
    (r'Migré', 'Migrated'),
    (r'migré', 'migrated'),
    (r'migrée', 'migrated'),
    (r'migrés', 'migrated'),
    (r'migrées', 'migrated'),
    (r'Déployé', 'Deployed'),
    (r'déployé', 'deployed'),
    (r'déployée', 'deployed'),
    (r'déployés', 'deployed'),
    (r'déployées', 'deployed'),
    (r'Publié', 'Published'),
    (r'publié', 'published'),
    (r'Publiée', 'Published'),
    (r'publiée', 'published'),
    (r'Publiés', 'Published'),
    (r'publiés', 'published'),
    (r'Publiées', 'Published'),
    (r'publiées', 'published'),
    (r'Distribué', 'Distributed'),
    (r'distribué', 'distributed'),
    (r'distribuée', 'distributed'),
    (r'distribués', 'distributed'),
    (r'distribuées', 'distributed'),
    (r'Intégré', 'Integrated'),
    (r'intégré', 'integrated'),
    (r'intégrée', 'integrated'),
    (r'intégrés', 'integrated'),
    (r'intégrées', 'integrated'),
    (r'Inclus', 'Included'),
    (r'inclus', 'included'),
    (r'incluse', 'included'),
    (r'incluses', 'included'),
    (r'Exclu', 'Excluded'),
    (r'exclu', 'excluded'),
    (r'exclue', 'excluded'),
    (r'exclus', 'excluded'),
    (r'exclues', 'excluded'),
    (r'Supprimé', 'Deleted'),
    (r'supprimé', 'deleted'),
    (r'Supprimée', 'Deleted'),
    (r'supprimée', 'deleted'),
    (r'Supprimés', 'Deleted'),
    (r'supprimés', 'deleted'),
    (r'Supprimées', 'Deleted'),
    (r'supprimées', 'deleted'),
    (r'Détruit', 'Destroyed'),
    (r'détruit', 'destroyed'),
    (r'détruite', 'destroyed'),
    (r'détruits', 'destroyed'),
    (r'détruites', 'destroyed'),
    (r'Effacé', 'Erased'),
    (r'effacé', 'erased'),
    (r'effacée', 'erased'),
    (r'effacés', 'erased'),
    (r'effacées', 'erased'),
    (r'Ajouté', 'Added'),
    (r'ajouté', 'added'),
    (r'Ajoutée', 'Added'),
    (r'ajoutée', 'added'),
    (r'Ajoutés', 'Added'),
    (r'ajoutés', 'added'),
    (r'Ajoutées', 'Added'),
    (r'ajoutées', 'added'),
    (r'Créé', 'Created'),
    (r'créé', 'created'),
    (r'Créée', 'Created'),
    (r'créée', 'created'),
    (r'Créés', 'Created'),
    (r'créés', 'created'),
    (r'Créées', 'Created'),
    (r'créées', 'created'),
    (r'Modifié', 'Modified'),
    (r'modifié', 'modified'),
    (r'Modifiée', 'Modified'),
    (r'modifiée', 'modified'),
    (r'Modifiés', 'Modified'),
    (r'modifiés', 'modified'),
    (r'Modifiées', 'Modified'),
    (r'modifiées', 'modified'),
    (r'Mis à jour', 'Updated'),
    (r'mis à jour', 'updated'),
    (r'Mise à jour', 'Update'),
    (r'mise à jour', 'update'),
    (r'Mises à jour', 'Updates'),
    (r'mises à jour', 'updates'),
    (r'Réinitialisé', 'Reset'),
    (r'réinitialisé', 'reset'),
    (r'réinitialisée', 'reset'),
    (r'réinitialisés', 'reset'),
    (r'réinitialisées', 'reset'),
    (r'Réinitialisation', 'Reset'),
    (r'réinitialisation', 'reset'),
    (r'Réinitialise', 'Resets'),
    (r'réinitialise', 'resets'),
    (r'Rafraîchi', 'Refreshed'),
    (r'rafraîchi', 'refreshed'),
    (r'rafraîchie', 'refreshed'),
    (r'rafraîchis', 'refreshed'),
    (r'rafraîchies', 'refreshed'),
    (r'Régénéré', 'Regenerated'),
    (r'régénéré', 'regenerated'),
    (r'régénérée', 'regenerated'),
    (r'régénérés', 'regenerated'),
    (r'régénérées', 'regenerated'),
    (r'Approuvé', 'Approved'),
    (r'approuvé', 'approved'),
    (r'approuvée', 'approved'),
    (r'approuvés', 'approved'),
    (r'approuvées', 'approved'),
    (r'Rejeté', 'Rejected'),
    (r'rejeté', 'rejected'),
    (r'rejetée', 'rejected'),
    (r'rejetés', 'rejected'),
    (r'rejetées', 'rejected'),
    (r'Accepté', 'Accepted'),
    (r'accepté', 'accepted'),
    (r'acceptée', 'accepted'),
    (r'acceptés', 'accepted'),
    (r'acceptées', 'accepted'),
    (r'Refusé', 'Refused'),
    (r'refusé', 'refused'),
    (r'refusée', 'refused'),
    (r'refusés', 'refused'),
    (r'refusées', 'refused'),
    (r'Confirmé', 'Confirmed'),
    (r'confirmé', 'confirmed'),
    (r'confirmée', 'confirmed'),
    (r'confirmés', 'confirmed'),
    (r'confirmées', 'confirmed'),
    (r'Annulé', 'Canceled'),
    (r'annulé', 'canceled'),
    (r'Annulée', 'Canceled'),
    (r'annulée', 'canceled'),
    (r'Annulés', 'Canceled'),
    (r'annulés', 'canceled'),
    (r'Annulées', 'Canceled'),
    (r'annulées', 'canceled'),
    (r'Clôturé', 'Closed'),
    (r'clôturé', 'closed'),
    (r'clôturée', 'closed'),
    (r'clôturés', 'closed'),
    (r'clôturées', 'closed'),
    (r'Verrouillé', 'Locked'),
    (r'verrouillé', 'locked'),
    (r'verrouillée', 'locked'),
    (r'verrouillés', 'locked'),
    (r'verrouillées', 'locked'),
    (r'Déverrouillé', 'Unlocked'),
    (r'déverrouillé', 'unlocked'),
    (r'déverrouillée', 'unlocked'),
    (r'déverrouillés', 'unlocked'),
    (r'déverrouillées', 'unlocked'),
    (r'Suspendu', 'Suspended'),
    (r'suspendu', 'suspended'),
    (r'suspendue', 'suspended'),
    (r'suspendus', 'suspended'),
    (r'suspendues', 'suspended'),
    (r'Désactivé', 'Deactivated'),
    (r'désactivé', 'deactivated'),
    (r'désactivée', 'deactivated'),
    (r'désactivés', 'deactivated'),
    (r'désactivées', 'deactivated'),
    (r'Expiré', 'Expired'),
    (r'expiré', 'expired'),
    (r'expirée', 'expired'),
    (r'expirés', 'expired'),
    (r'expirées', 'expired'),
    (r'Résilié', 'Terminated'),
    (r'résilié', 'terminated'),
    (r'résiliée', 'terminated'),
    (r'résiliés', 'terminated'),
    (r'résiliées', 'terminated'),
    (r'Révoqué', 'Revoked'),
    (r'révoqué', 'revoked'),
    (r'révoquée', 'revoked'),
    (r'révoqués', 'revoked'),
    (r'révoquées', 'revoked'),
    (r'Rétabli', 'Restored'),
    (r'rétabli', 'restored'),
    (r'rétablie', 'restored'),
    (r'rétablis', 'restored'),
    (r'rétablies', 'restored'),
    (r'Restauré', 'Restored'),
    (r'restauré', 'restored'),
    (r'restaurée', 'restored'),
    (r'restaurés', 'restored'),
    (r'restaurées', 'restored'),
    (r'Récupéré', 'Recovered'),
    (r'récupéré', 'recovered'),
    (r'récupérée', 'recovered'),
    (r'récupérés', 'recovered'),
    (r'récupérées', 'recovered'),
    (r'Sauvegardé', 'Backed up'),
    (r'sauvegardé', 'backed up'),
    (r'sauvegardée', 'backed up'),
    (r'sauvegardés', 'backed up'),
    (r'sauvegardées', 'backed up'),
    (r'Archivé', 'Archived'),
    (r'archivé', 'archived'),
    (r'Archivée', 'Archived'),
    (r'archivée', 'archived'),
    (r'Archivés', 'Archived'),
    (r'archivés', 'archived'),
    (r'Archivées', 'Archived'),
    (r'archivées', 'archived'),
    (r'Responsable', 'Manager'),
    (r'responsable', 'responsible'),
    (r'responsabilité', 'responsibility'),
    (r'Responsabilité', 'Responsibility'),
    (r'Responsabilités', 'Responsibilities'),
    (r'responsabilités', 'responsibilities'),
    (r'Auteur', 'Author'),
    (r'auteur', 'author'),
    (r'Créateur', 'Creator'),
    (r'créateur', 'creator'),
    (r'créatrice', 'creator'),
    (r'Propriétaire', 'Owner'),
    (r'propriétaire', 'owner'),
    (r'propriétaires', 'owners'),
    (r'Administrateur', 'Administrator'),
    (r'administrateur', 'administrator'),
    (r'administrateurs', 'administrators'),
    (r'Modérateur', 'Moderator'),
    (r'modérateur', 'moderator'),
    (r'modérateurs', 'moderators'),
    (r'Contributeur', 'Contributor'),
    (r'contributeur', 'contributor'),
    (r'contributeurs', 'contributors'),
    (r'Collaborateur', 'Collaborator'),
    (r'collaborateur', 'collaborator'),
    (r'collaborateurs', 'collaborators'),
    (r'Participant', 'Participant'),
    (r'participant', 'participant'),
    (r'participants', 'participants'),
    (r'Membre', 'Member'),
    (r'membre', 'member'),
    (r'membres', 'members'),
    (r'Invité', 'Guest'),
    (r'invité', 'invited'),
    (r'invitée', 'invited'),
    (r'invités', 'invited'),
    (r'invitées', 'invited'),
    (r'Observateur', 'Observer'),
    (r'observateur', 'observer'),
    (r'observateurs', 'observers'),
    (r'Vérificateur', 'Verifier'),
    (r'vérificateur', 'verifier'),
    (r'Approbateur', 'Approver'),
    (r'approbateur', 'approver'),
    (r'approbateurs', 'approvers'),
    (r'Signataire', 'Signatory'),
    (r'signataire', 'signatory'),
    (r'signataires', 'signatories'),
    (r'Destinataire', 'Recipient'),
    (r'destinataire', 'recipient'),
    (r'Destinataires', 'Recipients'),
    (r'destinataires', 'recipients'),
    (r'Expéditeur', 'Sender'),
    (r'expéditeur', 'sender'),
    (r'expéditeurs', 'senders'),
    (r'Émetteur', 'Issuer'),
    (r'émetteur', 'issuer'),
    (r'émetteurs', 'issuers'),
    (r'Fournisseur', 'Provider'),
    (r'fournisseur', 'provider'),
    (r'fournisseurs', 'providers'),
    (r'Consommateur', 'Consumer'),
    (r'consommateur', 'consumer'),
    (r'consommateurs', 'consumers'),
    (r'Producteur', 'Producer'),
    (r'producteur', 'producer'),
    (r'producteurs', 'producers'),
    (r'Utilisateur', 'User'),
    (r'utilisateur', 'user'),
    (r'Utilisateurs', 'Users'),
    (r'utilisateurs', 'users'),
    (r'Client', 'Client'),
    (r'client', 'client'),
    (r'clients', 'clients'),
    (r'Service', 'Service'),
    (r'service', 'service'),
    (r'services', 'services'),
    (r'Module', 'Module'),
    (r'module', 'module'),
    (r'modules', 'modules'),
    (r'Fonctionnalité', 'Feature'),
    (r'fonctionnalité', 'feature'),
    (r'fonctionnalités', 'features'),
    (r'Fonction', 'Function'),
    (r'fonction', 'function'),
    (r'fonctions', 'functions'),
    (r'Composant', 'Component'),
    (r'composant', 'component'),
    (r'composants', 'components'),
    (r'Entité', 'Entity'),
    (r'entité', 'entity'),
    (r'entités', 'entities'),
    (r'Objet', 'Object'),
    (r'objet', 'object'),
    (r'objets', 'objects'),
    (r'Classe', 'Class'),
    (r'classe', 'class'),
    (r'classes', 'classes'),
    (r'Interface', 'Interface'),
    (r'interface', 'interface'),
    (r'interfaces', 'interfaces'),
    (r'Méthode', 'Method'),
    (r'méthode', 'method'),
    (r'méthodes', 'methods'),
    (r'Attribut', 'Attribute'),
    (r'attribut', 'attribute'),
    (r'attributs', 'attributes'),
    (r'Propriété', 'Property'),
    (r'propriété', 'property'),
    (r'propriétés', 'properties'),
    (r'Champ', 'Field'),
    (r'champ', 'field'),
    (r'Champs', 'Fields'),
    (r'champs', 'fields'),
    (r'Variable', 'Variable'),
    (r'variable', 'variable'),
    (r'variables', 'variables'),
    (r'Paramètre', 'Parameter'),
    (r'paramètre', 'parameter'),
    (r'paramètres', 'parameters'),
    (r'Argument', 'Argument'),
    (r'argument', 'argument'),
    (r'arguments', 'arguments'),
    (r'Valeur', 'Value'),
    (r'valeur', 'value'),
    (r'Valeurs', 'Values'),
    (r'valeur', 'value'),
    (r'Valeurs', 'Values'),
    (r'Défaut', 'Default'),
    (r'défaut', 'default'),
    (r'Initial', 'Initial'),
    (r'initial', 'initial'),
    (r'initiale', 'initial'),
    (r'initiaux', 'initial'),
    (r'initiales', 'initial'),
    (r'Final', 'Final'),
    (r'final', 'final'),
    (r'finale', 'final'),
    (r'finaux', 'final'),
    (r'finales', 'final'),
    (r'Objectif', 'Objective'),
    (r'objectif', 'objective'),
    (r'objectifs', 'objectives'),
    (r'But', 'Goal'),
    (r'but', 'goal'),
    (r'buts', 'goals'),
    (r'Cible', 'Target'),
    (r'cible', 'target'),
    (r'cibles', 'targets'),
    (r'Résultat', 'Result'),
    (r'résultat', 'result'),
    (r'résultats', 'results'),
    (r'Sortie', 'Output'),
    (r'sortie', 'output'),
    (r'sorties', 'outputs'),
    (r'Entrée', 'Input'),
    (r'entrée', 'input'),
    (r'entrées', 'inputs'),
    (r'Source', 'Source'),
    (r'source', 'source'),
    (r'sources', 'sources'),
    (r'Destination', 'Destination'),
    (r'destination', 'destination'),
    (r'destinations', 'destinations'),
    (r'Cible', 'Target'),
    (r'cible', 'target'),
    (r'cibles', 'targets'),
    (r'Statique', 'Static'),
    (r'statique', 'static'),
    (r'statiques', 'static'),
    (r'Dynamique', 'Dynamic'),
    (r'dynamique', 'dynamic'),
    (r'dynamiques', 'dynamic'),
    (r'Asynchrone', 'Asynchronous'),
    (r'asynchrone', 'asynchronous'),
    (r'Synchrone', 'Synchronous'),
    (r'synchrone', 'synchronous'),
    (r'Réactif', 'Reactive'),
    (r'réactif', 'reactive'),
    (r'réactive', 'reactive'),
    (r'réactifs', 'reactive'),
    (r'réactives', 'reactive'),
    (r'Proactif', 'Proactive'),
    (r'proactif', 'proactive'),
    (r'proactive', 'proactive'),
    (r'proactifs', 'proactive'),
    (r'proactives', 'proactive'),
    (r'Adaptatif', 'Adaptive'),
    (r'adaptatif', 'adaptive'),
    (r'adaptative', 'adaptive'),
    (r'adaptatifs', 'adaptive'),
    (r'adaptatives', 'adaptive'),
    (r'Flexible', 'Flexible'),
    (r'flexible', 'flexible'),
    (r'flexibles', 'flexible'),
    (r'Extensible', 'Extensible'),
    (r'extensible', 'extensible'),
    (r'extensibles', 'extensible'),
    (r'Évolutif', 'Scalable'),
    (r'évolutif', 'scalable'),
    (r'évolutive', 'scalable'),
    (r'évolutifs', 'scalable'),
    (r'évolutives', 'scalable'),
    (r'Robuste', 'Robust'),
    (r'robuste', 'robust'),
    (r'robustes', 'robust'),
    (r'Fiable', 'Reliable'),
    (r'fiable', 'reliable'),
    (r'fiables', 'reliable'),
    (r'Résilient', 'Resilient'),
    (r'résilient', 'resilient'),
    (r'résiliente', 'resilient'),
    (r'résilients', 'resilient'),
    (r'résilientes', 'resilient'),
    (r'Performant', 'Performant'),
    (r'performant', 'performant'),
    (r'performante', 'performant'),
    (r'performants', 'performant'),
    (r'performantes', 'performant'),
    (r'Optimisé', 'Optimized'),
    (r'optimisé', 'optimized'),
    (r'optimisée', 'optimized'),
    (r'optimisés', 'optimized'),
    (r'optimisées', 'optimized'),
    (r'Efficace', 'Efficient'),
    (r'efficace', 'efficient'),
    (r'efficaces', 'efficient'),
    (r'Informatif', 'Informative'),
    (r'informatif', 'informative'),
    (r'informative', 'informative'),
    (r'informatifs', 'informative'),
    (r'informatives', 'informative'),
    (r'Descriptif', 'Descriptive'),
    (r'descriptif', 'descriptive'),
    (r'descriptive', 'descriptive'),
    (r'descriptifs', 'descriptive'),
    (r'descriptives', 'descriptive'),
    (r'Explicatif', 'Explanatory'),
    (r'explicatif', 'explanatory'),
    (r'explicative', 'explanatory'),
    (r'explicatifs', 'explanatory'),
    (r'explicatives', 'explanatory'),
    (r'Pratique', 'Practical'),
    (r'pratique', 'practical'),
    (r'pratiques', 'practical'),
    (r'Théorique', 'Theoretical'),
    (r'théorique', 'theoretical'),
    (r'théoriques', 'theoretical'),
    (r'Technique', 'Technical'),
    (r'technique', 'technical'),
    (r'techniques', 'technical'),
    (r'Fonctionnel', 'Functional'),
    (r'fonctionnel', 'functional'),
    (r'fonctionnelle', 'functional'),
    (r'fonctionnels', 'functional'),
    (r'fonctionnelles', 'functional'),
    (r'Structurel', 'Structural'),
    (r'structurel', 'structural'),
    (r'structurelle', 'structural'),
    (r'structurels', 'structural'),
    (r'structurelles', 'structural'),
    (r'Architectural', 'Architectural'),
    (r'architectural', 'architectural'),
    (r'architecturale', 'architectural'),
    (r'architecturaux', 'architectural'),
    (r'architecturales', 'architectural'),
    (r'Comportemental', 'Behavioral'),
    (r'comportemental', 'behavioral'),
    (r'comportementale', 'behavioral'),
    (r'comportementaux', 'behavioral'),
    (r'comportementales', 'behavioral'),
    (r'Agile', 'Agile'),
    (r'agile', 'agile'),
    (r'agiles', 'agile'),
    (r'Lean', 'Lean'),
    (r'lean', 'lean'),
    (r'Itératif', 'Iterative'),
    (r'itératif', 'iterative'),
    (r'itérative', 'iterative'),
    (r'itératifs', 'iterative'),
    (r'itératives', 'iterative'),
    (r'Inc rimental', 'Incremental'),
    (r'incrimental', 'incremental'),
    (r'incrimentale', 'incremental'),
    (r'incrimentaux', 'incremental'),
    (r'incrimentales', 'incremental'),
    (r'Collaboratif', 'Collaborative'),
    (r'collaboratif', 'collaborative'),
    (r'collaborative', 'collaborative'),
    (r'collaboratifs', 'collaborative'),
    (r'collaboratives', 'collaborative'),
    (r'Rationnel', 'Rational'),
    (r'rationnel', 'rational'),
    (r'rationnelle', 'rational'),
    (r'rationnels', 'rational'),
    (r'rationnelles', 'rational'),
    (r'Intuitif', 'Intuitive'),
    (r'intuitif', 'intuitive'),
    (r'intuitive', 'intuitive'),
    (r'intuitifs', 'intuitive'),
    (r'intuitives', 'intuitive'),
    (r'Naturel', 'Natural'),
    (r'naturel', 'natural'),
    (r'naturelle', 'natural'),
    (r'naturels', 'natural'),
    (r'naturelles', 'natural'),
    (r'Artificiel', 'Artificial'),
    (r'artificiel', 'artificial'),
    (r'artificielle', 'artificial'),
    (r'artificiels', 'artificial'),
    (r'artificielles', 'artificial'),
    (r'Intelligent', 'Intelligent'),
    (r'intelligent', 'intelligent'),
    (r'intelligente', 'intelligent'),
    (r'intelligents', 'intelligent'),
    (r'intelligentes', 'intelligent'),
    (r'Automatique', 'Automatic'),
    (r'automatique', 'automatic'),
    (r'automatiques', 'automatic'),
    (r'Manuel', 'Manual'),
    (r'manuel', 'manual'),
    (r'manuelle', 'manual'),
    (r'manuels', 'manual'),
    (r'manuelles', 'manual'),
    (r'Semi-automatique', 'Semi-automatic'),
    (r'semi-automatique', 'semi-automatic'),
    (r'semi-automatiques', 'semi-automatic'),
    (r'Temporaire', 'Temporary'),
    (r'temporaire', 'temporary'),
    (r'temporaires', 'temporary'),
    (r'Permanent', 'Permanent'),
    (r'permanent', 'permanent'),
    (r'permanente', 'permanent'),
    (r'permanents', 'permanent'),
    (r'permanentes', 'permanent'),
    (r'Définitif', 'Definitive'),
    (r'définitif', 'definitive'),
    (r'définitive', 'definitive'),
    (r'définitifs', 'definitive'),
    (r'définitives', 'definitive'),
    (r'Continu', 'Continuous'),
    (r'continu', 'continuous'),
    (r'continue', 'continuous'),
    (r'continus', 'continuous'),
    (r'continues', 'continuous'),
    (r'Discontinu', 'Discontinuous'),
    (r'discontinu', 'discontinuous'),
    (r'discontinue', 'discontinuous'),
    (r'discontinus', 'discontinuous'),
    (r'discontinues', 'discontinuous'),
    (r'Périodique', 'Periodic'),
    (r'périodique', 'periodic'),
    (r'périodiques', 'periodic'),
    (r'Régulier', 'Regular'),
    (r'régulier', 'regular'),
    (r'régulière', 'regular'),
    (r'réguliers', 'regular'),
    (r'régulières', 'regular'),
    (r'Irrégulier', 'Irregular'),
    (r'irrégulier', 'irregular'),
    (r'irrégulière', 'irregular'),
    (r'irréguliers', 'irregular'),
    (r'irrégulières', 'irregular'),
    (r'Fréquent', 'Frequent'),
    (r'fréquent', 'frequent'),
    (r'fréquente', 'frequent'),
    (r'fréquents', 'frequent'),
    (r'fréquentes', 'frequent'),
    (r'Rare', 'Rare'),
    (r'rare', 'rare'),
    (r'rares', 'rare'),
    (r'Occasionnel', 'Occasional'),
    (r'occasionnel', 'occasional'),
    (r'occasionnelle', 'occasional'),
    (r'occasionnels', 'occasional'),
    (r'occasionnelles', 'occasional'),
    (r'Tardif', 'Late'),
    (r'tardif', 'late'),
    (r'tardive', 'late'),
    (r'tardifs', 'late'),
    (r'tardives', 'late'),
    (r'Précoce', 'Early'),
    (r'précoce', 'early'),
    (r'précoces', 'early'),
    (r'Immédiat', 'Immediate'),
    (r'immédiat', 'immediate'),
    (r'immédiate', 'immediate'),
    (r'immédiats', 'immediate'),
    (r'immédiates', 'immediate'),
    (r'Différé', 'Deferred'),
    (r'différé', 'deferred'),
    (r'différée', 'deferred'),
    (r'différés', 'deferred'),
    (r'différées', 'deferred'),
    (r'Planifié', 'Scheduled'),
    (r'planifié', 'scheduled'),
    (r'planifiée', 'scheduled'),
    (r'planifiés', 'scheduled'),
    (r'planifiées', 'scheduled'),
    (r'Ordonnancé', 'Scheduled'),
    (r'ordonnancé', 'scheduled'),
    (r'ordonnancée', 'scheduled'),
    (r'ordonnancés', 'scheduled'),
    (r'ordonnancées', 'scheduled'),
    (r'Programmé', 'Scheduled'),
    (r'programmé', 'scheduled'),
    (r'programmée', 'scheduled'),
    (r'programmés', 'scheduled'),
    (r'programmées', 'scheduled'),
    (r'Reporté', 'Postponed'),
    (r'reporté', 'postponed'),
    (r'reportée', 'postponed'),
    (r'reportés', 'postponed'),
    (r'reportées', 'postponed'),
    (r'Repoussé', 'Deferred'),
    (r'repoussé', 'deferred'),
    (r'repoussée', 'deferred'),
    (r'repoussés', 'deferred'),
    (r'repoussées', 'deferred'),
    (r'Avancé', 'Advanced'),
    (r'avancé', 'advanced'),
    (r'avancée', 'advanced'),
    (r'avancés', 'advanced'),
    (r'avancées', 'advanced'),
    (r'Retardé', 'Delayed'),
    (r'retardé', 'delayed'),
    (r'retardée', 'delayed'),
    (r'retardés', 'delayed'),
    (r'retardées', 'delayed'),
    (r'Accéléré', 'Accelerated'),
    (r'accéléré', 'accelerated'),
    (r'accélérée', 'accelerated'),
    (r'accélérés', 'accelerated'),
    (r'accélérées', 'accelerated'),
    (r'Ralenti', 'Slowed'),
    (r'ralenti', 'slowed'),
    (r'ralentie', 'slowed'),
    (r'ralentis', 'slowed'),
    (r'ralenties', 'slowed'),
    (r'Stoppé', 'Stopped'),
    (r'stoppé', 'stopped'),
    (r'stoppée', 'stopped'),
    (r'stoppés', 'stopped'),
    (r'stoppées', 'stopped'),
    (r'Arrêté', 'Stopped'),
    (r'arrêté', 'stopped'),
    (r'arrêtée', 'stopped'),
    (r'arrêtés', 'stopped'),
    (r'arrêtées', 'stopped'),
    (r'Repris', 'Resumed'),
    (r'repris', 'resumed'),
    (r'reprise', 'resumed'),
    (r'repris', 'resumed'),
    (r'reprises', 'resumed'),
    (r'Continué', 'Continued'),
    (r'continué', 'continued'),
    (r'continuée', 'continued'),
    (r'continués', 'continued'),
    (r'continuées', 'continued'),
    (r'Maintenu', 'Maintained'),
    (r'maintenu', 'maintained'),
    (r'maintenue', 'maintained'),
    (r'maintenus', 'maintained'),
    (r'maintenues', 'maintained'),
    (r'Conservé', 'Preserved'),
    (r'conservé', 'preserved'),
    (r'conservée', 'preserved'),
    (r'conservés', 'preserved'),
    (r'conservées', 'preserved'),
    (r'Préservé', 'Preserved'),
    (r'préservé', 'preserved'),
    (r'préservée', 'preserved'),
    (r'préservés', 'preserved'),
    (r'préservées', 'preserved'),
    (r'Augmenté', 'Increased'),
    (r'augmenté', 'increased'),
    (r'augmentée', 'increased'),
    (r'augmentés', 'increased'),
    (r'augmentées', 'increased'),
    (r'Diminué', 'Decreased'),
    (r'diminué', 'decreased'),
    (r'diminuée', 'decreased'),
    (r'diminués', 'decreased'),
    (r'diminuées', 'decreased'),
    (r'Réduit', 'Reduced'),
    (r'réduit', 'reduced'),
    (r'réduite', 'reduced'),
    (r'réduits', 'reduced'),
    (r'réduites', 'reduced'),
    (r'Étendu', 'Extended'),
    (r'étendu', 'extended'),
    (r'étendue', 'extended'),
    (r'étendus', 'extended'),
    (r'étendues', 'extended'),
    (r'Limite', 'Limited'),
    (r'limite', 'limit'),
    (r'limites', 'limits'),
    (r'Limitations', 'Limitations'),
    (r'limitations', 'limitations'),
    (r'Contrainte', 'Constraint'),
    (r'contrainte', 'constraint'),
    (r'contraintes', 'constraints'),
    (r'Restriction', 'Restriction'),
    (r'restriction', 'restriction'),
    (r'restrictions', 'restrictions'),
    (r'Exception', 'Exception'),
    (r'exception', 'exception'),
    (r'exceptions', 'exceptions'),
    (r'Erreur', 'Error'),
    (r'erreur', 'error'),
    (r'Erreurs', 'Errors'),
    (r'erreurs', 'errors'),
    (r'Défaillance', 'Failure'),
    (r'défaillance', 'failure'),
    (r'défaillances', 'failures'),
    (r'Échec', 'Failure'),
    (r'échec', 'failure'),
    (r'échecs', 'failures'),
    (r'Panique', 'Panic'),
    (r'panique', 'panic'),
    (r'Débogage', 'Debugging'),
    (r'débogage', 'debugging'),
    (r'Journalisation', 'Logging'),
    (r'journalisation', 'logging'),
    (r'Traçabilité', 'Traceability'),
    (r'traçabilité', 'traceability'),
    (r'Surveillance', 'Monitoring'),
    (r'surveillance', 'monitoring'),
    (r'Métrique', 'Metric'),
    (r'métrique', 'metric'),
    (r'métriques', 'metrics'),
    (r'Indicateur', 'Indicator'),
    (r'indicateur', 'indicator'),
    (r'indicateurs', 'indicators'),
    (r'Mesure', 'Measurement'),
    (r'mesure', 'measurement'),
    (r'mesures', 'measurements'),
    (r'Évaluation', 'Evaluation'),
    (r'évaluation', 'evaluation'),
    (r'évaluations', 'evaluations'),
    (r'Analyse', 'Analysis'),
    (r'analyse', 'analysis'),
    (r'analyses', 'analyses'),
    (r'Statistique', 'Statistic'),
    (r'statistique', 'statistic'),
    (r'Statistiques', 'Statistics'),
    (r'statistiques', 'statistics'),
    (r'Rapport', 'Report'),
    (r'rapport', 'report'),
    (r'rapports', 'reports'),
    (r'Tableau', 'Dashboard'),
    (r'tableau', 'dashboard'),
    (r'Tableaux', 'Dashboards'),
    (r'tableaux', 'dashboards'),
    (r'Graphique', 'Chart'),
    (r'graphique', 'chart'),
    (r'Graphiques', 'Charts'),
    (r'graphiques', 'charts'),
    (r'Courbe', 'Curve'),
    (r'courbe', 'curve'),
    (r'courbes', 'curves'),
    (r'Histogramme', 'Histogram'),
    (r'histogramme', 'histogram'),
    (r'Camembert', 'Pie chart'),
    (r'camembert', 'pie chart'),
    (r'Diagramme', 'Diagram'),
    (r'diagramme', 'diagram'),
    (r'Diagrammes', 'Diagrams'),
    (r'diagrammes', 'diagrams'),
    (r'Carte', 'Map'),
    (r'carte', 'map'),
    (r'Cartes', 'Maps'),
    (r'cartes', 'maps'),
    (r'Calendrier', 'Calendar'),
    (r'calendrier', 'calendar'),
    (r'calendriers', 'calendars'),
    (r'Planning', 'Planning'),
    (r'planning', 'planning'),
    (r'plannings', 'plannings'),
    (r'Agenda', 'Agenda'),
    (r'agenda', 'agenda'),
    (r'Agendas', 'Agendas'),
    (r'agendas', 'agendas'),
    (r'Échéancier', 'Schedule'),
    (r'échéancier', 'schedule'),
    (r'échéanciers', 'schedules'),
    (r'Timeline', 'Timeline'),
    (r'timeline', 'timeline'),
    (r'timelines', 'timelines'),
    (r'Chronologie', 'Chronology'),
    (r'chronologie', 'chronology'),
    (r'chronologies', 'chronologies'),
    (r'Séquence', 'Sequence'),
    (r'séquence', 'sequence'),
    (r'séquences', 'sequences'),
    (r'Ordre', 'Order'),
    (r'ordre', 'order'),
    (r'ordres', 'orders'),
    (r'Hiérarchie', 'Hierarchy'),
    (r'hiérarchie', 'hierarchy'),
    (r'hiérarchies', 'hierarchies'),
    (r'Structure', 'Structure'),
    (r'structure', 'structure'),
    (r'Structures', 'Structures'),
    (r'structures', 'structures'),
    (r'Organisation', 'Organization'),
    (r'organisation', 'organization'),
    (r'organisations', 'organizations'),
    (r'Configuration', 'Configuration'),
    (r'configuration', 'configuration'),
    (r'configurations', 'configurations'),
    (r'Définition', 'Definition'),
    (r'définition', 'definition'),
    (r'définitions', 'definitions'),
    (r'Implémentation', 'Implementation'),
    (r'implémentation', 'implementation'),
    (r'implémentations', 'implementations'),
    (r'Intégration', 'Integration'),
    (r'intégration', 'integration'),
    (r'intégrations', 'integrations'),
    (r'Migration', 'Migration'),
    (r'migration', 'migration'),
    (r'migrations', 'migrations'),
    (r'Déploiement', 'Deployment'),
    (r'déploiement', 'deployment'),
    (r'déploiements', 'deployments'),
    (r'Installation', 'Installation'),
    (r'installation', 'installation'),
    (r'installations', 'installations'),
    (r'Mise à niveau', 'Upgrade'),
    (r'mise à niveau', 'upgrade'),
    (r'Mises à niveau', 'Upgrades'),
    (r'mises à niveau', 'upgrades'),
    (r'Mise à jour', 'Update'),
    (r'mise à jour', 'update'),
    (r'Mises à jour', 'Updates'),
    (r'mises à jour', 'updates'),
    (r'Correctif', 'Patch'),
    (r'correctif', 'patch'),
    (r'correctifs', 'patches'),
    (r'Mise à jour', 'Update'),
    (r'mise à jour', 'update'),
    (r'Mises à jour', 'Updates'),
    (r'mises à jour', 'updates'),
    (r'Version', 'Version'),
    (r'version', 'version'),
    (r'versions', 'versions'),
    (r'Release', 'Release'),
    (r'release', 'release'),
    (r'releases', 'releases'),
    (r'Build', 'Build'),
    (r'build', 'build'),
    (r'builds', 'builds'),
    (r'Compilation', 'Compilation'),
    (r'compilation', 'compilation'),
    (r'compilations', 'compilations'),
    (r'Exécution', 'Execution'),
    (r'exécution', 'execution'),
    (r'exécutions', 'executions'),
    (r'Construction', 'Construction'),
    (r'construction', 'construction'),
    (r'constructions', 'constructions'),
    (r'Génération', 'Generation'),
    (r'génération', 'generation'),
    (r'générations', 'generations'),
    (r'Production', 'Production'),
    (r'production', 'production'),
    (r'productions', 'productions'),
    (r'Développement', 'Development'),
    (r'développement', 'development'),
    (r'développements', 'developments'),
    (r'Test', 'Test'),
    (r'test', 'test'),
    (r'tests', 'tests'),
    (r'Vérification', 'Verification'),
    (r'vérification', 'verification'),
    (r'vérifications', 'verifications'),
    (r'Validation', 'Validation'),
    (r'validation', 'validation'),
    (r'validations', 'validations'),
    (r'Certification', 'Certification'),
    (r'certification', 'certification'),
    (r'certifications', 'certifications'),
    (r'Qualification', 'Qualification'),
    (r'qualification', 'qualification'),
    (r'qualifications', 'qualifications'),
    (r'Accréditation', 'Accreditation'),
    (r'accréditation', 'accreditation'),
    (r'accréditations', 'accreditations'),
    (r'Habilitation', 'Clearance'),
    (r'habilitation', 'clearance'),
    (r'habilitations', 'clearances'),
    (r'Agrément', 'Approval'),
    (r'agrément', 'approval'),
    (r'agréments', 'approvals'),
    (r'Autorisation', 'Authorization'),
    (r'autorisation', 'authorization'),
    (r'autorisations', 'authorizations'),
    (r'Consentement', 'Consent'),
    (r'consentement', 'consent'),
    (r'consentements', 'consents'),
    (r'Approbation', 'Approval'),
    (r'approbation', 'approval'),
    (r'approbations', 'approvals'),
    (r'Refus', 'Refusal'),
    (r'refus', 'refusal'),
    (r'Rejet', 'Rejection'),
    (r'rejet', 'rejection'),
    (r'rejets', 'rejections'),
    (r'Déni', 'Denial'),
    (r'déni', 'denial'),
    (r'dénis', 'denials'),
    (r'Opposition', 'Opposition'),
    (r'opposition', 'opposition'),
    (r'oppositions', 'oppositions'),
    (r'Contestation', 'Dispute'),
    (r'contestation', 'dispute'),
    (r'contestations', 'disputes'),
    (r'Réclamation', 'Claim'),
    (r'réclamation', 'claim'),
    (r'réclamations', 'claims'),
    (r'Demande', 'Request'),
    (r'demande', 'request'),
    (r'Demandes', 'Requests'),
    (r'demandes', 'requests'),
    (r'Sollicitation', 'Solicitation'),
    (r'sollicitation', 'solicitation'),
    (r'sollicitations', 'solicitations'),
    (r'Requête', 'Request'),
    (r'requête', 'request'),
    (r'Requêtes', 'Requests'),
    (r'requêtes', 'requests'),
    (r'Transaction', 'Transaction'),
    (r'transaction', 'transaction'),
    (r'transactions', 'transactions'),
    (r'Opération', 'Operation'),
    (r'opération', 'operation'),
    (r'Opérations', 'Operations'),
    (r'opérations', 'operations'),
    (r'Action', 'Action'),
    (r'action', 'action'),
    (r'actions', 'actions'),
    (r'Activité', 'Activity'),
    (r'activité', 'activity'),
    (r'Activités', 'Activities'),
    (r'activités', 'activities'),
    (r'Événement', 'Event'),
    (r'événement', 'event'),
    (r'événements', 'events'),
    (r'Évènement', 'Event'),
    (r'évènement', 'event'),
    (r'évènements', 'events'),
    (r'Incident', 'Incident'),
    (r'incident', 'incident'),
    (r'incidents', 'incidents'),
    (r'Problème', 'Problem'),
    (r'problème', 'problem'),
    (r'problèmes', 'problems'),
    (r'Dysfonctionnement', 'Malfunction'),
    (r'dysfonctionnement', 'malfunction'),
    (r'dysfonctionnements', 'malfunctions'),
    (r'Panne', 'Failure'),
    (r'panne', 'failure'),
    (r'pannes', 'failures'),
]


def process_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    original = content
    change_count = 0

    for pattern, replacement in replacements:
        new_content, count = re.subn(pattern, replacement, content)
        if count > 0:
            change_count += count
            content = new_content

    if change_count > 0:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        relpath = os.path.relpath(filepath, "C:\\Users\\SURFACE\\Desktop\\collabix\\backend\\src\\main\\java\\com\\trio\\backend")
        print(f"  Modified: {relpath} (+{change_count} changes)")

    return change_count


total_changes = 0
total_files = 0

for base_dir in target_dirs:
    if not os.path.isdir(base_dir):
        print(f"Directory not found: {base_dir}")
        continue

    for root, dirs, files in os.walk(base_dir):
        for filename in files:
            if filename.endswith('.java'):
                filepath = os.path.join(root, filename)
                changes = process_file(filepath)
                if changes > 0:
                    total_changes += changes
                    total_files += 1

print(f"\n=== FINAL SUMMARY ===")
print(f"Files modified: {total_files}")
print(f"Total changes: {total_changes}")
