import { BookMarked, Star, RefreshCw, Download } from 'lucide-react';
import { IconButton } from '../../ui/IconButton';

export function HistoryHeader() {
  return (
    <div className="flex items-start justify-between gap-4">
      <div>
        <div className="flex items-center gap-2">
          <BookMarked className="h-5 w-5 text-accent-600 dark:text-accent-400" />
          <h1 className="text-page font-semibold text-text-primary">AI History</h1>
        </div>
        <p className="mt-0.5 text-caption text-text-tertiary">
          Browse every conversation, report and summary previously generated by Collabix AI.
        </p>
      </div>
      <div className="flex items-center gap-1 shrink-0">
        <IconButton label="Export history" variant="ghost" size="sm" onClick={() => {}}>
          <Download className="h-[18px] w-[18px]" />
        </IconButton>
        <IconButton label="Favorites" variant="ghost" size="sm" onClick={() => {}}>
          <Star className="h-[18px] w-[18px]" />
        </IconButton>
        <IconButton label="Refresh" variant="ghost" size="sm" onClick={() => {}}>
          <RefreshCw className="h-[18px] w-[18px]" />
        </IconButton>
      </div>
    </div>
  );
}
