ALTER TABLE ai_models
    ADD COLUMN IF NOT EXISTS created_by UUID,
    ADD COLUMN IF NOT EXISTS updated_by UUID,
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE ai_models ALTER COLUMN updated_at DROP NOT NULL;
ALTER TABLE ai_models ALTER COLUMN updated_at SET DEFAULT NULL;
