-- =========================================
-- Collabix HR Manager Access
-- Version 20260844
-- Grant MANAGER full HR management permissions
-- so HR managers can run every HR workflow
-- exposed by the frontend (employees, candidates,
-- interviews, onboarding, performance reviews,
-- attendance, documents, skills, notes, notifications).
-- =========================================

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r CROSS JOIN permissions p
WHERE r.name = 'MANAGER'
  AND p.code IN (
    'EMPLOYEE_READ', 'EMPLOYEE_CREATE', 'EMPLOYEE_UPDATE', 'EMPLOYEE_DELETE',
    'CANDIDATE_READ', 'CANDIDATE_CREATE', 'CANDIDATE_UPDATE', 'CANDIDATE_DELETE',
    'CANDIDATE_ATTACHMENT_READ', 'CANDIDATE_ATTACHMENT_UPLOAD', 'CANDIDATE_ATTACHMENT_UPDATE', 'CANDIDATE_ATTACHMENT_DELETE',
    'INTERVIEW_READ', 'INTERVIEW_CREATE', 'INTERVIEW_UPDATE', 'INTERVIEW_DELETE', 'INTERVIEW_CANCEL',
    'INTERVIEW_CALENDAR_VIEW',
    'ONBOARDING_READ', 'ONBOARDING_CREATE', 'ONBOARDING_UPDATE', 'ONBOARDING_DELETE', 'ONBOARDING_TASK_MANAGE',
    'PERFORMANCE_REVIEW_READ', 'PERFORMANCE_REVIEW_CREATE', 'PERFORMANCE_REVIEW_UPDATE', 'PERFORMANCE_REVIEW_DELETE',
    'PERFORMANCE_REVIEW_SUBMIT', 'PERFORMANCE_REVIEW_APPROVE',
    'ATTENDANCE_READ', 'ATTENDANCE_CREATE', 'ATTENDANCE_UPDATE', 'ATTENDANCE_DELETE',
    'EMPLOYEE_DOCUMENT_READ', 'EMPLOYEE_DOCUMENT_UPLOAD', 'EMPLOYEE_DOCUMENT_UPDATE', 'EMPLOYEE_DOCUMENT_DELETE', 'EMPLOYEE_DOCUMENT_VERIFY',
    'EMPLOYEE_SKILL_READ', 'EMPLOYEE_SKILL_CREATE', 'EMPLOYEE_SKILL_UPDATE', 'EMPLOYEE_SKILL_DELETE',
    'RECRUITER_NOTE_READ', 'RECRUITER_NOTE_CREATE', 'RECRUITER_NOTE_UPDATE', 'RECRUITER_NOTE_DELETE',
    'HR_NOTIFICATION_READ', 'HR_NOTIFICATION_DISMISS'
)
ON CONFLICT (role_id, permission_id) DO NOTHING;
