package com.trio.backend.ai.enums;

public enum AITask {
    GENERAL_CHAT,
    ANALYTICS_SUMMARY,
    ANALYTICS_INSIGHTS,
    ANALYTICS_RECOMMENDATIONS,
    HANDOVER_SUMMARY,
    HANDOVER_EXECUTIVE_REPORT,
    HANDOVER_RISK_ANALYSIS,
    HANDOVER_CONTINUITY,
    KNOWLEDGE_SEARCH,
    DOCUMENT_SUMMARY,
    DOCUMENT_EXPLANATION,
    REPORT_GENERATION,
    REPORT_SUMMARY,
    REPORT_EXECUTIVE_SUMMARY
}
